import{describe,it,expect}from'vitest';import{readFileSync}from'node:fs';import{evaluateAuthority,executionGate}from'../src/authority.js';
const h='a'.repeat(64),now='2026-09-29T10:00:00.000Z';
const base={actorEntityId:'actor-a',actionType:'COMMUNICATE',targetResourceId:'resource-a',license:{id:'lic-a',licenseClass:2,endorsements:['EXT'],scope:{actionTypes:['COMMUNICATE'],resourceIds:['resource-a']},validFrom:'2026-09-01T00:00:00.000Z',validUntil:'2026-10-01T00:00:00.000Z',evidenceHash:h},mission:{id:'mission-a',maxLicenseClass:2,scope:{actionTypes:['COMMUNICATE'],resourceIds:['resource-a']},startsAt:'2026-09-01T00:00:00.000Z',expiresAt:'2026-10-01T00:00:00.000Z',evidenceHash:h},authorityStatus:'ACTIVE' as const,freshness:'CURRENT' as const,budget:'WITHIN_BUDGET' as const,law:'SUPPORTED' as const,now};
describe('authority/delegation/approval adversarial gate',()=>{
 it('expired, revoked and suspended authority never execute',()=>{for(const authorityStatus of ['EXPIRED','REVOKED','SUSPENDED'] as const){const r=evaluateAuthority({...base,authorityStatus});expect(r.decision).toBe('NOT_AUTHORIZED');expect(executionGate(r)).toBe('DENY_EXECUTION')}});
 it('wrong action, resource and mission scope are denied',()=>{expect(evaluateAuthority({...base,actionType:'TRANSACT'}).decision).not.toBe('AUTHORIZED');expect(evaluateAuthority({...base,targetResourceId:'resource-b'}).decision).toBe('NOT_AUTHORIZED');expect(evaluateAuthority({...base,mission:{...base.mission,scope:{actionTypes:['OBSERVE'],resourceIds:['resource-a']}}}).decision).toBe('NOT_AUTHORIZED')});
 it('policy uncertainty fails closed after policy changes',()=>{const r=evaluateAuthority({...base,actionType:'FUTURE_POLICY_ACTION'});expect(r.decision).not.toBe('AUTHORIZED');expect(r.reasons).toContain('ACTION_AUTHORITY_POLICY_NOT_ESTABLISHED')});
 it('delegation expiry and scope overflow are denied',()=>{expect(evaluateAuthority({...base,delegation:{delegatedClass:2,endorsements:['EXT'],scope:{actionTypes:['COMMUNICATE'],resourceIds:['resource-a']},expiresAt:'2026-09-29T09:59:59.000Z',evidenceHash:h}}).decision).toBe('NOT_AUTHORIZED');expect(evaluateAuthority({...base,delegation:{delegatedClass:2,endorsements:['EXT'],scope:{actionTypes:['OBSERVE'],resourceIds:['resource-a']},expiresAt:'2026-09-30T10:00:00.000Z',evidenceHash:h}}).decision).toBe('NOT_AUTHORIZED')});
 it('execution before approval fails closed and rejection denies',()=>{const pending=evaluateAuthority({...base,approval:{required:true,decision:'UNKNOWN',evidenceHash:null}});expect(pending.decision).toBe('UNKNOWN');expect(executionGate(pending)).toBe('HOLD_UNKNOWN');const denied=evaluateAuthority({...base,approval:{required:true,decision:'DENIED',evidenceHash:h}});expect(denied.decision).toBe('NOT_AUTHORIZED');expect(executionGate(denied)).toBe('DENY_EXECUTION')});
 it('database blocks self approval, duplicate approval replay, delegation cycles and parent-expiry overflow',()=>{const m=readFileSync(new URL('../db/064_authority_async_integrity.sql',import.meta.url),'utf8');expect(m).toContain('universe_approval_no_self_approval');expect(m).toContain('universe_approval_replay_uq');expect(m).toContain('delegation cycle rejected');expect(m).toContain('delegation cannot outlive parent delegation')});
});
