import test from 'node:test';import assert from 'node:assert/strict';import{evaluateAuthority}from'../src/authority.js';
const h='a'.repeat(64), now='2026-09-29T10:00:00.000Z';
const base={actorEntityId:'actor',actionType:'SEND',license:{id:'l',licenseClass:2,validFrom:'2026-09-01T00:00:00.000Z',validUntil:'2026-10-01T00:00:00.000Z',evidenceHash:h},mission:{id:'m',maxLicenseClass:2,startsAt:'2026-09-01T00:00:00.000Z',expiresAt:'2026-10-01T00:00:00.000Z',evidenceHash:h},authorityStatus:'ACTIVE' as const,freshness:'CURRENT' as const,budget:'WITHIN_BUDGET' as const,law:'SUPPORTED' as const,now};
test('authorizes only fully established active authority',()=>assert.equal(evaluateAuthority(base).decision,'AUTHORIZED'));
test('missing mission fails closed to UNKNOWN',()=>assert.equal(evaluateAuthority({...base,mission:null}).decision,'UNKNOWN'));
test('revoked authority is not authorized',()=>assert.equal(evaluateAuthority({...base,authorityStatus:'REVOKED'}).decision,'NOT_AUTHORIZED'));
test('stale authority is UNKNOWN rather than allowed',()=>assert.equal(evaluateAuthority({...base,freshness:'STALE'}).decision,'UNKNOWN'));
test('required approval without evidence is UNKNOWN',()=>assert.equal(evaluateAuthority({...base,approval:{required:true,decision:'APPROVED'}}).decision,'UNKNOWN'));
test('over budget is not authorized',()=>assert.equal(evaluateAuthority({...base,budget:'OVER_BUDGET'}).decision,'NOT_AUTHORIZED'));
test('unknown law evidence fails closed',()=>assert.equal(evaluateAuthority({...base,law:'UNKNOWN'}).decision,'UNKNOWN'));
test('expired mission is not authorized',()=>assert.equal(evaluateAuthority({...base,now:'2026-10-02T00:00:00.000Z'}).decision,'NOT_AUTHORIZED'));
