import{describe,it,expect}from'vitest';import{runCollector,evidenceDigest}from'../src/collectors.js';
describe('Satellite collector contract',()=>{
 it('preserves valid observed evidence',async()=>{const c={key:'code',version:'1',collect:async(s:{type:string;id:string})=>({collectorKey:'code',collectorVersion:'1',subjectType:s.type,subjectId:s.id,health:'HEALTHY' as const,coverage:'OBSERVED' as const,observedAt:'2026-09-29T10:00:00Z',collectedAt:'2026-09-29T10:00:01Z',payload:{ok:true},evidenceHash:evidenceDigest({collectorKey:'code',collectorVersion:'1',subjectType:s.type,subjectId:s.id,health:'HEALTHY',coverage:'OBSERVED',observedAt:'2026-09-29T10:00:00Z',payload:{ok:true},limitations:[]}),limitations:[]})};expect((await runCollector(c,{type:'repo',id:'r'})).coverage).toBe('OBSERVED')});
 it('converts collector failure to UNKNOWN instead of PASS',async()=>{const c={key:'cost',version:'1',collect:async()=>{throw Error('provider down')}};const r=await runCollector(c,{type:'account',id:'a'});expect(r.coverage).toBe('UNKNOWN');expect(r.health).toBe('UNKNOWN')});
 it('rejects identity mismatch into UNKNOWN',async()=>{const c={key:'policy',version:'1',collect:async()=>({collectorKey:'other',collectorVersion:'1',subjectType:'x',subjectId:'y',health:'HEALTHY' as const,coverage:'OBSERVED' as const,observedAt:'x',collectedAt:'x',payload:{},evidenceHash:'a'.repeat(64),limitations:[]})};expect((await runCollector(c,{type:'x',id:'y'})).coverage).toBe('UNKNOWN')});

 it('converts future timestamps to UNKNOWN',async()=>{const future=new Date(Date.now()+10*60*1000).toISOString();const c={key:'future',version:'1',collect:async(s:{type:string;id:string})=>{const limitations:string[]=[];const payload={ok:true};return{collectorKey:'future',collectorVersion:'1',subjectType:s.type,subjectId:s.id,health:'HEALTHY' as const,coverage:'OBSERVED' as const,observedAt:future,collectedAt:future,payload,evidenceHash:evidenceDigest({collectorKey:'future',collectorVersion:'1',subjectType:s.type,subjectId:s.id,health:'HEALTHY',coverage:'OBSERVED',observedAt:future,payload,limitations}),limitations}}};const r=await runCollector(c,{type:'repo',id:'r'});expect(r.coverage).toBe('UNKNOWN');expect(r.health).toBe('UNKNOWN');expect(r.limitations[0]).toBe('INVALID_COLLECTOR_CHRONOLOGY')});
 it('rejects invalid runtime health and coverage values',async()=>{const c:any={key:'bad-enum',version:'1',collect:async(s:any)=>{const limitations:string[]=[];const payload={};const observedAt=new Date().toISOString();return{collectorKey:'bad-enum',collectorVersion:'1',subjectType:s.type,subjectId:s.id,health:'SUPER_HEALTHY',coverage:'PASS',observedAt,collectedAt:observedAt,payload,evidenceHash:evidenceDigest({collectorKey:'bad-enum',collectorVersion:'1',subjectType:s.type,subjectId:s.id,health:'SUPER_HEALTHY',coverage:'PASS',observedAt,payload,limitations}),limitations}}};expect((await runCollector(c,{type:'x',id:'y'})).coverage).toBe('UNKNOWN')});
 it('rejects oversized collector limitations',async()=>{const c:any={key:'meta',version:'1',collect:async(s:any)=>{const limitations=['x'.repeat(1001)];const payload={};const observedAt=new Date().toISOString();return{collectorKey:'meta',collectorVersion:'1',subjectType:s.type,subjectId:s.id,health:'HEALTHY',coverage:'OBSERVED',observedAt,collectedAt:observedAt,payload,evidenceHash:evidenceDigest({collectorKey:'meta',collectorVersion:'1',subjectType:s.type,subjectId:s.id,health:'HEALTHY',coverage:'OBSERVED',observedAt,payload,limitations}),limitations}}};const r=await runCollector(c,{type:'x',id:'y'});expect(r.limitations[0]).toBe('INVALID_COLLECTOR_LIMITATIONS')});
});
