import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { createStore } from '../src/db.js';
import { canGrant } from '../src/security-gate.js';
import { canReadTenantRecord } from '../src/tenant.js';
import { evaluateAuthority, executionGate } from '../src/authority.js';
import type { VerificationRecord } from '../src/domain/media.js';
const h=(s:string)=>createHash('sha256').update(s).digest('hex');
const base={actorEntityId:'00000000-0000-4000-8000-000000000001',actionType:'ACT',targetResourceId:'00000000-0000-4000-8000-000000000002',license:{id:'00000000-0000-4000-8000-000000000003',licenseClass:3,scope:{actionTypes:['ACT'],resourceIds:['00000000-0000-4000-8000-000000000002']},validFrom:'2026-01-01T00:00:00Z',validUntil:'2027-01-01T00:00:00Z',evidenceHash:h('license')},mission:{id:'00000000-0000-4000-8000-000000000004',maxLicenseClass:3,scope:{actionTypes:['ACT'],resourceIds:['00000000-0000-4000-8000-000000000002']},startsAt:'2026-01-01T00:00:00Z',expiresAt:'2027-01-01T00:00:00Z',evidenceHash:h('mission')},authorityStatus:'ACTIVE' as const,freshness:'CURRENT' as const,now:'2026-09-30T00:00:00Z'};
describe('Constellation Phase 1 identity and isolation adversarial runtime',()=>{
it('1 authentication: invalid expired revoked and rotated API credentials fail closed',async()=>{const s=createStore(undefined);const good=await s.createApiKey('galaxy-a','good','viewer');expect(await s.authenticateApiKey('mp_invalid')).toBeNull();const expired=await s.createApiKey('galaxy-a','expired','viewer','2020-01-01T00:00:00Z');expect(await s.authenticateApiKey(expired.key)).toBeNull();const revoked=await s.createApiKey('galaxy-a','revoked','viewer');await s.revokeApiKey('galaxy-a',revoked.id);expect(await s.authenticateApiKey(revoked.key)).toBeNull();const rotated=await s.rotateApiKey('galaxy-a',good.id,'replacement','viewer');expect(await s.authenticateApiKey(good.key)).toBeNull();expect((await s.authenticateApiKey(rotated!.key))?.organizationId).toBe('galaxy-a');await s.close()});
it('3 Sun identity: tenant identity cannot be substituted by a foreign object',()=>{const foreign={asset:{organizationId:'galaxy-b'}} as VerificationRecord;expect(canReadTenantRecord({keyId:'a',organizationId:'galaxy-a',role:'organization_admin'},foreign)).toBe(false)});
it('4 RBAC: lower roles cannot grant themselves higher authority',()=>{expect(canGrant('viewer','organization_admin')).toBe(false);expect(canGrant('creator','platform_admin')).toBe(false);expect(canGrant('organization_admin','platform_admin')).toBe(false);expect(canGrant('platform_admin','super_admin')).toBe(false)});
it('6 authority: unknown stale inactive or out-of-scope authority never executes',()=>{expect(executionGate(evaluateAuthority({...base,authorityStatus:'UNKNOWN'}))).toBe('HOLD_UNKNOWN');expect(executionGate(evaluateAuthority({...base,freshness:'STALE'}))).toBe('HOLD_UNKNOWN');expect(executionGate(evaluateAuthority({...base,authorityStatus:'REVOKED'}))).toBe('DENY_EXECUTION');expect(executionGate(evaluateAuthority({...base,targetResourceId:'00000000-0000-4000-8000-000000000099'}))).toBe('DENY_EXECUTION')});
it('7 delegation: expired or excessive delegation cannot authorize',()=>{expect(executionGate(evaluateAuthority({...base,delegation:{delegatedClass:3,scope:{actionTypes:['ACT']},expiresAt:'2026-01-01T00:00:00Z',evidenceHash:h('delegation')}}))).toBe('DENY_EXECUTION');expect(executionGate(evaluateAuthority({...base,delegation:{delegatedClass:7,scope:{actionTypes:['ACT']},expiresAt:'2026-12-01T00:00:00Z',evidenceHash:h('delegation2')}}))).toBe('DENY_EXECUTION')});
it('8 approval bypass: missing forged expired or denied approval never executes',()=>{for(const approval of [{required:true,decision:'UNKNOWN' as const,evidenceHash:h('x')},{required:true,decision:'APPROVED' as const,evidenceHash:'forged'},{required:true,decision:'APPROVED' as const,evidenceHash:h('ok'),validUntil:'2026-01-01T00:00:00Z'}])expect(executionGate(evaluateAuthority({...base,approval}))).toBe('HOLD_UNKNOWN');expect(executionGate(evaluateAuthority({...base,approval:{required:true,decision:'DENIED',evidenceHash:h('deny')}}))).toBe('DENY_EXECUTION')});
});