import{describe,it,expect}from'vitest';import{verifiedEnforcement}from'../src/enforcement.js';import{createKernelStore}from'../src/evidence-store.js';
const done='2026-09-29T22:00:01.000Z';const receipt=(status:'ALLOWED'|'BLOCKED'|'FAILED',id='r1')=>({receiptId:id,externalEventId:'evt-'+id,status,enforcedAt:done,details:{provider:'gateway'}});
const base={organizationId:'org-a',policyEvaluationId:'00000000-0000-4000-8000-000000000001',subjectType:'AI',subjectId:'agent-1',actionType:'SEND',enforcementPoint:'gateway',attemptedAt:'2026-09-29T22:00:00.000Z'};
describe('real enforcement proof',()=>{
 it('only calls an externally identified verified blocked receipt PREVENTED',async()=>{const k=createKernelStore();const r=await verifiedEnforcement({...base,decision:'BLOCK',outcome:'BLOCKED',completedAt:done,providerReceipt:receipt('BLOCKED')},k);expect(r.preventionState).toBe('PREVENTED');expect(r.externalReceiptId).toBe('r1');expect(r.externalEventId).toBe('evt-r1');expect(r.evidenceId).toMatch(/^[0-9a-f-]{36}$/);expect((await k.bindings('org-a','GOVERNANCE',r.id))).toHaveLength(1)});
 it('does not call allow/failure prevented',async()=>{const k=createKernelStore();expect((await verifiedEnforcement({...base,decision:'ALLOW',outcome:'ALLOWED',completedAt:done,providerReceipt:receipt('ALLOWED')},k)).preventionState).toBe('NOT_PREVENTED');expect((await verifiedEnforcement({...base,decision:'BLOCK',outcome:'FAILED',completedAt:done,providerReceipt:receipt('FAILED')},k)).preventionState).toBe('NOT_PREVENTED')});
 it('keeps unavailable and unknown evidence-free and never prevented',async()=>{const k=createKernelStore();const u=await verifiedEnforcement({...base,decision:'BLOCK',outcome:'UNAVAILABLE',providerReceipt:null},k);expect(u.preventionState).toBe('UNAVAILABLE');expect(u.evidenceId).toBeNull();expect(u.externalReceiptId).toBeNull();const x=await verifiedEnforcement({...base,decision:'BLOCK',outcome:'UNKNOWN',providerReceipt:null},k);expect(x.preventionState).toBe('UNKNOWN')});
 it('rejects forged blocked outcome without a block decision or completion',async()=>{const k=createKernelStore();await expect(verifiedEnforcement({...base,decision:'ALLOW',outcome:'BLOCKED',completedAt:done,providerReceipt:receipt('BLOCKED')},k)).rejects.toThrow('BLOCKED_REQUIRES_BLOCK_DECISION');await expect(verifiedEnforcement({...base,decision:'BLOCK',outcome:'BLOCKED',providerReceipt:receipt('BLOCKED')},k)).rejects.toThrow('BLOCKED_REQUIRES_COMPLETION')});
 it('rejects empty arbitrary or mismatched receipts',async()=>{const k=createKernelStore();await expect(verifiedEnforcement({...base,decision:'BLOCK',outcome:'BLOCKED',completedAt:done,providerReceipt:{}},k)).rejects.toThrow('VERIFIED_ENFORCEMENT_RECEIPT_REQUIRED');await expect(verifiedEnforcement({...base,decision:'BLOCK',outcome:'BLOCKED',completedAt:done,providerReceipt:receipt('ALLOWED')},k)).rejects.toThrow('ENFORCEMENT_RECEIPT_OUTCOME_MISMATCH');await expect(verifiedEnforcement({...base,decision:'BLOCK',outcome:'BLOCKED',completedAt:done,providerReceipt:{...receipt('BLOCKED'),enforcedAt:'2026-09-29T22:00:02.000Z'}},k)).rejects.toThrow('ENFORCEMENT_RECEIPT_TIME_MISMATCH')});
 it('keeps evidence tenant scoped',async()=>{const k=createKernelStore();const r=await verifiedEnforcement({...base,decision:'BLOCK',outcome:'BLOCKED',completedAt:done,providerReceipt:receipt('BLOCKED')},k);expect(await k.bindings('org-b','GOVERNANCE',r.id)).toHaveLength(0)});
});
