import{describe,it,expect,vi,afterEach}from'vitest';import{runCollector}from'../src/collectors.js';import{httpDiscoveryCollector}from'../src/shadow-ai-collectors.js';import{scannerReady}from'../src/security/scanner-readiness.js';import{scanForMalware}from'../src/security/malware.js';import{classify,deliverClaimed,defaultDeliveryPolicy}from'../src/webhook-delivery.js';import{createIdempotencyStore}from'../src/idempotency-store.js';import{writeFile,mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
afterEach(()=>vi.unstubAllGlobals());
describe('failure and chaos gate',()=>{
 it('scanner death is never interpreted as clean',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>{throw Error('scanner killed')}));expect(await scannerReady('https://scanner.example','token',50)).toBe(false);const d=await mkdtemp(join(tmpdir(),'media-chaos-')),p=join(d,'x');await writeFile(p,'x');await expect(scanForMalware(p,1,'application/octet-stream','https://scanner.example','token',50)).rejects.toThrow('scanner killed');await rm(d,{recursive:true,force:true})});
 it('collector death degrades to UNKNOWN not observed',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>{throw Error('collector killed')}));const r=await runCollector(httpDiscoveryCollector({provider:'OPENAI',baseUrl:'https://collector.example',token:'secret',path:'/usage'}),{type:'ORGANIZATION',id:'o'});expect(r.health).toBe('UNKNOWN');expect(r.coverage).toBe('UNKNOWN');expect(r.payload).toBeNull()});
 it('webhook dependency death retries and never becomes delivered',()=>{expect(classify(1,null)).toBe('RETRY');expect(classify(defaultDeliveryPolicy.maxAttempts,null)).toBe('DEAD');expect(classify(1,503)).not.toBe('DELIVERED')});
 it('duplicate concurrent execution claims cannot both execute',async()=>{const s=createIdempotencyStore();const f='a'.repeat(64);const results=await Promise.all(Array.from({length:25},()=>s.claim('tenant','same',f)));expect(results.filter(x=>x.status==='CLAIMED')).toHaveLength(1);expect(results.filter(x=>x.status==='IN_PROGRESS')).toHaveLength(24);await s.close()});
 it('different payload under duplicate key conflicts instead of replaying success',async()=>{const s=createIdempotencyStore();expect((await s.claim('tenant','same','a'.repeat(64))).status).toBe('CLAIMED');expect((await s.claim('tenant','same','b'.repeat(64))).status).toBe('CONFLICT');await s.close()});
 it('delivery finalization failure cannot manufacture DELIVERED',async()=>{const store:any={signingKey:async()=>({id:'k',secret:'x'.repeat(32)}),subscription:async()=>({id:'s',url:'https://hooks.example.com'}),finish:async()=>{throw Error('database killed before commit')}};const fetcher:any=async()=>new Response('',{status:200});await expect(deliverClaimed(store,{token:'t',rows:[{id:'1',organization_id:'o',subscription_id:'s',payload:{x:1},attempt_count:0}]},defaultDeliveryPolicy,fetcher)).rejects.toThrow('database killed before commit')});
});