import{describe,expect,it,vi}from'vitest';import{httpDiscoveryCollector,isPrivateAddress,safeBase}from'../src/shadow-ai-collectors.js';import{runCollector}from'../src/collectors.js';
const cfg={provider:'OPENAI' as const,baseUrl:'https://collector.example',token:'secret-token',path:'/usage'};
describe('real Shadow AI collector boundary',()=>{
 it('turns returned provider records into observed evidence',async()=>{const transport=vi.fn(async()=>({status:200,body:JSON.stringify({data:[{id:'u1',model:'gpt-x',application:'editor',observed_at:'2026-09-29T20:00:00Z'}]})}));const r=await runCollector(httpDiscoveryCollector(cfg,transport),{type:'ORGANIZATION',id:'org'});expect(r.health).toBe('HEALTHY');expect(r.coverage).toBe('OBSERVED');expect((r.payload as any).rows).toHaveLength(1)});
 it('does not turn an empty provider response into no-AI proof',async()=>{const transport=vi.fn(async()=>({status:200,body:JSON.stringify({data:[]})}));const r=await runCollector(httpDiscoveryCollector(cfg,transport),{type:'ORGANIZATION',id:'org'});expect(r.coverage).toBe('PARTIAL');expect(r.limitations.join(' ')).toMatch(/absence is not proof/i)});
 it('fails closed to UNKNOWN when provider is unavailable or malformed',async()=>{const down=await runCollector(httpDiscoveryCollector(cfg,async()=>({status:503,body:'nope'})),{type:'ORGANIZATION',id:'org'});expect(down.coverage).toBe('UNKNOWN');expect(down.health).toBe('UNKNOWN');expect((await runCollector(httpDiscoveryCollector(cfg,async()=>({status:200,body:'{bad'})),{type:'ORGANIZATION',id:'org'})).coverage).toBe('UNKNOWN')});
 it('blocks literal private-network collector targets before transport',async()=>{const transport=vi.fn(async()=>({status:200,body:'{}'}));const r=await runCollector(httpDiscoveryCollector({...cfg,baseUrl:'https://127.0.0.1'},transport),{type:'ORGANIZATION',id:'org'});expect(r.coverage).toBe('UNKNOWN');expect(transport).not.toHaveBeenCalled()});
 it('recognizes private and special-use addresses',()=>{for(const ip of ['127.0.0.1','10.0.0.1','192.168.1.4','172.16.0.1','169.254.1.1','100.64.0.1','::1','fc00::1','fe80::1'])expect(isPrivateAddress(ip)).toBe(true);expect(isPrivateAddress('8.8.8.8')).toBe(false)});
 it('forbids embedded URL credentials and cross-origin paths',async()=>{expect(()=>safeBase('https://u:p@collector.example')).toThrow('COLLECTOR_URL_CREDENTIALS_FORBIDDEN');const r=await runCollector(httpDiscoveryCollector({...cfg,path:'https://other.example/x'},async()=>({status:200,body:'{}'})),{type:'ORGANIZATION',id:'org'});expect(r.coverage).toBe('UNKNOWN');expect(r.limitations[0]).toBe('COLLECTOR_CROSS_ORIGIN_PATH_FORBIDDEN')});
 it('normalizes bounded provider strings and drops control-character values',async()=>{const transport=async()=>({status:200,body:JSON.stringify({data:[{id:'ok',model:'bad\u0000value',application:'e\u0301'}]})});const r=await runCollector(httpDiscoveryCollector(cfg,transport),{type:'ORGANIZATION',id:'org'});expect((r.payload as any).rows[0].model).toBeUndefined();expect((r.payload as any).rows[0].application).toBe('é')});
 it('does not promote unsupported garbage objects to observed coverage',async()=>{const transport=async()=>({status:200,body:JSON.stringify({data:[{garbage:'x'},{nested:{bad:true}}]})});const r=await runCollector(httpDiscoveryCollector(cfg,transport),{type:'ORGANIZATION',id:'org'});expect(r.coverage).toBe('PARTIAL');expect((r.payload as any).rows).toHaveLength(0)});
});
