ALTER TABLE evidence_bindings DROP CONSTRAINT IF EXISTS evidence_bindings_domain_check;
ALTER TABLE evidence_bindings ADD CONSTRAINT evidence_bindings_domain_check CHECK(domain IN('AI_FLIGHT','AI_ACCOUNTABILITY','AI_INVENTORY','AI_BEHAVIOR','GOVERNANCE','MEDIA','CONSTELLATION','INCIDENT','COMPLIANCE','BILLING','REPORTING','EXPORT','OBSERVATION'));
