import postgres from 'postgres';import{randomUUID}from'node:crypto';
export type ValueState='OBSERVED'|'CALCULATED'|'CONFIGURED'|'ESTIMATED'|'UNKNOWN';export type Attribution='AI'|'HUMAN'|'TOOL'|'INTEGRATION'|'EXTERNAL'|'MIXED'|'UNKNOWN';
export type Metric='AI_EXECUTION_TIME'|'MODEL_COST'|'TOKEN_COST'|'TOOL_COST'|'API_COST'|'INFRASTRUCTURE_COST'|'RETRY'|'FAILED_ACTION'|'REPEATED_INSTRUCTION'|'CORRECTION'|'BACKTRACK'|'UNDO'|'REWORK'|'HUMAN_INTERVENTION'|'HUMAN_WAIT_TIME'|'HUMAN_CORRECTION_TIME'|'RECOVERY_DURATION'|'TIME_SAVED'|'COST_AVOIDED'|'SUCCESSFUL_ACTION'|'FIRST_ATTEMPT_COMPLETION'|'AUTONOMOUS_COMPLETION';
export interface Entry{id:string;aiId:string;eventId:string|null;metricType:Metric;value:number;unit:'MILLISECONDS'|'COUNT'|'TOKENS'|'USD'|'CAD'|'SECONDS'|'MINUTES';valueState:ValueState;attribution:Attribution;evidenceHash:string;source:string;occurredAt:string;calculation:Record<string,unknown>}
export interface Statement{aiId:string;coverage:'SUPPORTED'|'PARTIAL'|'UNKNOWN';entries:Entry[];totals:{observedMoney:Record<string,number>;estimatedMoney:Record<string,number>;calculatedMoney:Record<string,number>;configuredMoney:Record<string,number>;retries:number;interventions:number;correctionMinutes:number;timeSavedMinutes:number};unknownPercentage:number;note:string}
export interface AccountabilityStore{ready():Promise<boolean>;append(org:string,input:Omit<Entry,'id'>):Promise<Entry|null>;statement(org:string,aiId:string):Promise<Statement>;close():Promise<void>}
const hashOk=(s:string)=>/^[a-f0-9]{64}$/.test(s);const money=new Set(['USD','CAD']);
export function createAccountabilityStore(url?:string):AccountabilityStore{return url?new Pg(postgres(url,{prepare:false})):new Mem()}
function summarize(aiId:string,entries:Entry[]):Statement{const totals={observedMoney:{} as Record<string,number>,estimatedMoney:{} as Record<string,number>,calculatedMoney:{} as Record<string,number>,configuredMoney:{} as Record<string,number>,retries:0,interventions:0,correctionMinutes:0,timeSavedMinutes:0};for(const e of entries){if(money.has(e.unit)){const b=e.valueState==='OBSERVED'?totals.observedMoney:e.valueState==='ESTIMATED'?totals.estimatedMoney:e.valueState==='CALCULATED'?totals.calculatedMoney:e.valueState==='CONFIGURED'?totals.configuredMoney:null;if(b)b[e.unit]=(b[e.unit]||0)+e.value}if(e.metricType==='RETRY')totals.retries+=e.value;if(e.metricType==='HUMAN_INTERVENTION')totals.interventions+=e.value;if(e.metricType==='HUMAN_CORRECTION_TIME')totals.correctionMinutes+=e.unit==='MINUTES'?e.value:e.unit==='SECONDS'?e.value/60:e.unit==='MILLISECONDS'?e.value/60000:0;if(e.metricType==='TIME_SAVED')totals.timeSavedMinutes+=e.unit==='MINUTES'?e.value:e.unit==='SECONDS'?e.value/60:e.unit==='MILLISECONDS'?e.value/60000:0}const unknown=entries.filter(x=>x.valueState==='UNKNOWN'||x.attribution==='UNKNOWN').length;return{aiId,coverage:!entries.length?'UNKNOWN':unknown?'PARTIAL':'SUPPORTED',entries,totals,unknownPercentage:entries.length?Math.round(unknown/entries.length*10000)/100:100,note:'Observed, calculated, configured and estimated values are intentionally separated. Net value is not asserted without sufficient evidence.'}}
class Mem implements AccountabilityStore{private rows:{org:string;e:Entry}[]=[];private ai=new Set<string>();registerAi(org:string,id:string){this.ai.add(org+':'+id)}async ready(){return true}async append(org:string,i:Omit<Entry,'id'>){if(!hashOk(i.evidenceHash))throw Error('INVALID_EVIDENCE_HASH');if(!this.ai.has(org+':'+i.aiId))return null;const e={id:randomUUID(),...i,occurredAt:new Date(i.occurredAt).toISOString()};this.rows.push({org,e});return structuredClone(e)}async statement(org:string,aiId:string){return summarize(aiId,this.rows.filter(x=>x.org===org&&x.e.aiId===aiId).map(x=>structuredClone(x.e)))}async close(){this.rows=[]}}
const map=(r:any):Entry=>({id:r.id,aiId:r.ai_id,eventId:r.event_id,metricType:r.metric_type,value:Number(r.value),unit:r.unit,valueState:r.value_state,attribution:r.attribution,evidenceHash:r.evidence_hash,source:r.source,occurredAt:r.occurred_at.toISOString(),calculation:r.calculation||{}});
class Pg implements AccountabilityStore{constructor(private sql:postgres.Sql){}async ready(){try{await this.sql`SELECT 1 FROM ai_accountability_entries LIMIT 0`;return true}catch{return false}}async append(org:string,i:Omit<Entry,'id'>){if(!hashOk(i.evidenceHash))throw Error('INVALID_EVIDENCE_HASH');const r=await this.sql<any[]>`INSERT INTO ai_accountability_entries(id,organization_id,ai_id,event_id,metric_type,value,unit,value_state,attribution,evidence_hash,source,occurred_at,calculation) SELECT ${randomUUID()},${org},${i.aiId},${i.eventId},${i.metricType},${i.value},${i.unit},${i.valueState},${i.attribution},${i.evidenceHash},${i.source},${i.occurredAt},${JSON.stringify(i.calculation)} WHERE EXISTS(SELECT 1 FROM ai_identities WHERE organization_id=${org} AND id=${i.aiId}) RETURNING *`;return r[0]?map(r[0]):null}async statement(org:string,aiId:string){const r=await this.sql<any[]>`SELECT * FROM ai_accountability_entries WHERE organization_id=${org} AND ai_id=${aiId} ORDER BY occurred_at,id`;return summarize(aiId,r.map(map))}async close(){await this.sql.end({timeout:5})}}
