import postgres from 'postgres';
import {randomUUID} from 'node:crypto';
import type {EvidenceState} from './reconciliation.js';
export type NodeType='AI'|'MODEL'|'TOOL'|'API'|'DATABASE'|'HUMAN'|'OBSERVER'|'POLICY'|'DEPLOYMENT'|'EVIDENCE_SOURCE'|'UNKNOWN';
export type Phenomenon='CONNECTION'|'ORBIT'|'WORMHOLE'|'GRAVITY'|'DESCENDANT'|'TRANSIENT';
export interface ConstellationNode{id:string;organizationId:string;nodeType:NodeType;label:string;evidenceState:EvidenceState;aiIdentityId:string|null;metadata:Record<string,unknown>;firstObservedAt:string;lastObservedAt:string}
export interface ConstellationEdge{id:string;organizationId:string;fromNodeId:string;toNodeId:string;relationType:string;phenomenon:Phenomenon;evidenceState:EvidenceState;evidenceRefs:string[];firstObservedAt:string;lastObservedAt:string}
export interface VisibilityGap{id:string;organizationId:string;nodeId:string|null;gapType:'BLACK_HOLE'|'NEBULA';reason:string;evidenceRefs:string[];observedAt:string;resolvedAt:string|null}
export interface ConstellationStore{addNode(org:string,input:Omit<ConstellationNode,'id'|'organizationId'>):Promise<ConstellationNode>;addEdge(org:string,input:Omit<ConstellationEdge,'id'|'organizationId'>):Promise<ConstellationEdge>;addGap(org:string,input:Omit<VisibilityGap,'id'|'organizationId'|'resolvedAt'>):Promise<VisibilityGap>;snapshot(org:string,at?:string):Promise<{nodes:ConstellationNode[];edges:ConstellationEdge[];gaps:VisibilityGap[];semantics:Record<string,string>}>;close():Promise<void>}
const semantics={WORMHOLE:'Evidence-backed crossing between otherwise separated systems or environments.',BLACK_HOLE:'Visibility ends here. This does not imply malicious or harmful activity.',NEBULA:'Partial signals exist, but identity or relationships are unresolved.',GRAVITY:'Dependency concentration derived from observed relationships; not a risk verdict.'};
export function createConstellationStore(url?:string):ConstellationStore{return url?new PgStore(postgres(url,{prepare:false})):new MemoryStore()}
class MemoryStore implements ConstellationStore{nodes:ConstellationNode[]=[];edges:ConstellationEdge[]=[];gaps:VisibilityGap[]=[];async addNode(o:string,i:any){const r={id:randomUUID(),organizationId:o,...i};this.nodes.push(r);return structuredClone(r)}async addEdge(o:string,i:any){if(!i.evidenceRefs?.length)throw new Error('EVIDENCE_REQUIRED');const r={id:randomUUID(),organizationId:o,...i};this.edges.push(r);return structuredClone(r)}async addGap(o:string,i:any){const r={id:randomUUID(),organizationId:o,...i,resolvedAt:null};this.gaps.push(r);return structuredClone(r)}async snapshot(o:string,at=new Date().toISOString()){const t=Date.parse(at);const nodes=this.nodes.filter(n=>n.organizationId===o&&Date.parse(n.firstObservedAt)<=t);const ids=new Set(nodes.map(n=>n.id));return {nodes:structuredClone(nodes),edges:structuredClone(this.edges.filter(e=>e.organizationId===o&&ids.has(e.fromNodeId)&&ids.has(e.toNodeId)&&Date.parse(e.firstObservedAt)<=t)),gaps:structuredClone(this.gaps.filter(g=>g.organizationId===o&&Date.parse(g.observedAt)<=t&&(!g.resolvedAt||Date.parse(g.resolvedAt)>t))),semantics}}async close(){}}
const node=(r:any):ConstellationNode=>({id:r.id,organizationId:r.organization_id,nodeType:r.node_type,label:r.label,evidenceState:r.evidence_state,aiIdentityId:r.ai_identity_id,metadata:r.metadata,firstObservedAt:r.first_observed_at.toISOString(),lastObservedAt:r.last_observed_at.toISOString()});
const edge=(r:any):ConstellationEdge=>({id:r.id,organizationId:r.organization_id,fromNodeId:r.from_node_id,toNodeId:r.to_node_id,relationType:r.relation_type,phenomenon:r.phenomenon,evidenceState:r.evidence_state,evidenceRefs:r.evidence_refs,firstObservedAt:r.first_observed_at.toISOString(),lastObservedAt:r.last_observed_at.toISOString()});
class PgStore implements ConstellationStore{constructor(private sql:postgres.Sql){}async addNode(o:string,i:any){const r=await this.sql<any[]>`INSERT INTO constellation_nodes(id,organization_id,node_type,label,evidence_state,ai_identity_id,metadata,first_observed_at,last_observed_at) VALUES(${randomUUID()},${o},${i.nodeType},${i.label},${i.evidenceState},${i.aiIdentityId},${this.sql.json(i.metadata)},${i.firstObservedAt},${i.lastObservedAt}) RETURNING *`;return node(r[0])}async addEdge(o:string,i:any){if(!i.evidenceRefs?.length)throw new Error('EVIDENCE_REQUIRED');const exists=await this.sql`SELECT id FROM constellation_nodes WHERE organization_id=${o} AND id IN (${i.fromNodeId},${i.toNodeId})`;if(exists.length!==2)throw new Error('NODE_NOT_FOUND');const r=await this.sql<any[]>`INSERT INTO constellation_edges(id,organization_id,from_node_id,to_node_id,relation_type,phenomenon,evidence_state,evidence_refs,first_observed_at,last_observed_at) VALUES(${randomUUID()},${o},${i.fromNodeId},${i.toNodeId},${i.relationType},${i.phenomenon},${i.evidenceState},${this.sql.json(i.evidenceRefs)},${i.firstObservedAt},${i.lastObservedAt}) RETURNING *`;return edge(r[0])}async addGap(o:string,i:any){const id=randomUUID();await this.sql`INSERT INTO constellation_visibility_gaps(id,organization_id,node_id,gap_type,reason,evidence_refs,observed_at) VALUES(${id},${o},${i.nodeId},${i.gapType},${i.reason},${this.sql.json(i.evidenceRefs)},${i.observedAt})`;return{id,organizationId:o,...i,resolvedAt:null}}async snapshot(o:string,at=new Date().toISOString()){const ns=(await this.sql<any[]>`SELECT * FROM constellation_nodes WHERE organization_id=${o} AND first_observed_at<=${at} ORDER BY first_observed_at`).map(node);const es=(await this.sql<any[]>`SELECT * FROM constellation_edges WHERE organization_id=${o} AND first_observed_at<=${at} ORDER BY first_observed_at`).map(edge);const gs=await this.sql<any[]>`SELECT * FROM constellation_visibility_gaps WHERE organization_id=${o} AND observed_at<=${at} AND (resolved_at IS NULL OR resolved_at>${at}) ORDER BY observed_at`;return{nodes:ns,edges:es,gaps:gs.map(r=>({id:r.id,organizationId:r.organization_id,nodeId:r.node_id,gapType:r.gap_type,reason:r.reason,evidenceRefs:r.evidence_refs,observedAt:r.observed_at.toISOString(),resolvedAt:r.resolved_at?.toISOString()??null})),semantics}}async close(){await this.sql.end({timeout:5})}}
