import postgres from 'postgres';
import { randomUUID } from 'node:crypto';
export type EntityType='AI_AGENT'|'MODEL'|'HUMAN'|'TOOL'|'API'|'DATABASE'|'OBSERVER'|'POLICY'|'SYSTEM'|'WORKLOAD'|'CREDENTIAL'|'ARTIFACT'|'UNKNOWN';
export type EvidenceState='OBSERVED'|'VERIFIED'|'DECLARED'|'UNKNOWN'|'STALE'|'CONFLICTING'|'UNAVAILABLE';
export type RelationshipType='ORBIT'|'CLUSTER'|'WORMHOLE'|'DEPENDENCY'|'INTERACTION'|'PROVENANCE'|'OBSERVATION'|'POLICY_APPLIES'|'TRANSIENT'|'GRAVITY'|'OXYGEN';
export type ConstellationEventType='SUPERNOVA'|'BLACK_HOLE'|'NEBULA'|'CHANGE'|'BOUNDARY'|'VISIBILITY_LOSS'|'UFO'|'SPACE_DEBRIS';
export interface Entity{id:string;identityKey:string;entityType:EntityType;name:string;evidenceState:EvidenceState;evidenceHash:string;source:string;firstObservedAt:string;lastObservedAt:string;metadata:Record<string,unknown>;knownAt?:string}
export interface Relationship{id:string;fromEntityId:string;toEntityId:string;relationshipType:RelationshipType;evidenceState:EvidenceState;evidenceHash:string;source:string;observedAt:string;endedAt:string|null;metadata:Record<string,unknown>;knownAt?:string}
export interface ConstellationEvent{id:string;eventType:ConstellationEventType;entityId:string|null;relationshipId:string|null;evidenceState:EvidenceState;summary:string;evidenceHash:string;source:string;occurredAt:string;metadata:Record<string,unknown>;knownAt?:string}
export interface Snapshot{organizationId:string;asOf:string;entities:Entity[];relationships:Relationship[];events:ConstellationEvent[];coverage:{state:'OBSERVED'|'UNKNOWN';note:string}}
export interface ConstellationStore{ready():Promise<boolean>;addEntity(org:string,input:Omit<Entity,'id'|'knownAt'>):Promise<Entity>;addRelationship(org:string,input:Omit<Relationship,'id'|'knownAt'>):Promise<Relationship|null>;addEvent(org:string,input:Omit<ConstellationEvent,'id'|'knownAt'>):Promise<ConstellationEvent|null>;snapshot(org:string,asOf:string,limit?:number):Promise<Snapshot>;close():Promise<void>}
const validHash=(x:string)=>/^[a-f0-9]{64}$/.test(x);
const iso=(x:string)=>new Date(x).toISOString();
const established=(s:EvidenceState)=>s==='OBSERVED'||s==='VERIFIED';
const assertEntitySemantics=(i:Omit<Entity,'id'|'knownAt'>)=>{if(!/^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,199}$/.test(i.identityKey))throw new Error('INVALID_ENTITY_IDENTITY_KEY');if(!validHash(i.evidenceHash))throw new Error('INVALID_EVIDENCE_HASH');if(Date.parse(i.lastObservedAt)<Date.parse(i.firstObservedAt))throw new Error('INVALID_ENTITY_OBSERVATION_WINDOW')};
const assertRelationshipSemantics=(i:Omit<Relationship,'id'|'knownAt'>)=>{if(i.fromEntityId===i.toEntityId)throw new Error('SELF_RELATIONSHIP_NOT_ALLOWED');if(!validHash(i.evidenceHash))throw new Error('INVALID_EVIDENCE_HASH');if(i.endedAt&&Date.parse(i.endedAt)<=Date.parse(i.observedAt))throw new Error('INVALID_RELATIONSHIP_WINDOW');if(i.relationshipType==='WORMHOLE'){if(!established(i.evidenceState))throw new Error('WORMHOLE_REQUIRES_OBSERVED_EVIDENCE');const m=i.metadata as Record<string,unknown>;if(typeof m.proofId!=='string'||!/^[0-9a-f-]{36}$/i.test(m.proofId))throw new Error('WORMHOLE_PROOF_REQUIRED');if(typeof m.transactionId!=='string'||m.transactionId.length<1||m.transactionId.length>200)throw new Error('WORMHOLE_TRANSACTION_REQUIRED');if(typeof m.protocol!=='string'||m.protocol.length<1||m.protocol.length>80)throw new Error('WORMHOLE_PROTOCOL_REQUIRED');if(m.direction!=='OUTBOUND'&&m.direction!=='INBOUND'&&m.direction!=='BIDIRECTIONAL')throw new Error('WORMHOLE_DIRECTION_REQUIRED');if(typeof m.proofDigest!=='string'||!validHash(m.proofDigest))throw new Error('WORMHOLE_PROOF_DIGEST_REQUIRED')}};
const assertEventSemantics=(i:Omit<ConstellationEvent,'id'|'knownAt'>)=>{if(!validHash(i.evidenceHash))throw new Error('INVALID_EVIDENCE_HASH');if((i.eventType==='SUPERNOVA'||i.eventType==='CHANGE')&&!established(i.evidenceState))throw new Error('CHANGE_REQUIRES_OBSERVED_EVIDENCE');if(i.eventType==='BLACK_HOLE'||i.eventType==='VISIBILITY_LOSS'){if(!['UNKNOWN','STALE','UNAVAILABLE','CONFLICTING'].includes(i.evidenceState))throw new Error('VISIBILITY_GAP_REQUIRES_LIMITED_EVIDENCE_STATE');const m=i.metadata as Record<string,unknown>;if(!['NO_SIGNAL','STALE_SIGNAL','COLLECTOR_UNAVAILABLE','PERMISSION_GAP','COVERAGE_GAP','CONFLICTING_SIGNAL'].includes(String(m.gapType||'')))throw new Error('VISIBILITY_GAP_TYPE_REQUIRED');if(typeof m.observer!=='string'||m.observer.length<1||m.observer.length>160)throw new Error('VISIBILITY_GAP_OBSERVER_REQUIRED');if(typeof m.lastSeenAt!=='string'||!Number.isFinite(Date.parse(m.lastSeenAt)))throw new Error('VISIBILITY_GAP_LAST_SEEN_REQUIRED');const forbidden=JSON.stringify(m).toLowerCase();if(/malicious|malware|breach|compromised|noncompliant|unsafe/.test(forbidden))throw new Error('VISIBILITY_GAP_CANNOT_ASSERT_RISK_CONCLUSION')}}if(i.eventType==='NEBULA'){if(!['DECLARED','UNKNOWN','STALE','CONFLICTING','UNAVAILABLE'].includes(i.evidenceState))throw new Error('NEBULA_REQUIRES_UNRESOLVED_EVIDENCE_STATE');const m=i.metadata as Record<string,unknown>;if(!['PARTIAL_IDENTITY','PARTIAL_RELATIONSHIP','CONFLICTING_OBSERVATIONS','INCOMPLETE_PROVENANCE','UNRESOLVED_CLASSIFICATION','OTHER'].includes(String(m.unresolvedType||'')))throw new Error('NEBULA_UNRESOLVED_TYPE_REQUIRED');if(typeof m.unresolvedQuestion!=='string'||m.unresolvedQuestion.trim().length<1||m.unresolvedQuestion.length>500)throw new Error('NEBULA_UNRESOLVED_QUESTION_REQUIRED');if(!Array.isArray(m.observationHashes)||m.observationHashes.length<1||m.observationHashes.length>50||!m.observationHashes.every(x=>typeof x==='string'&&validHash(x)))throw new Error('NEBULA_OBSERVATIONS_REQUIRED');const forbidden=JSON.stringify(m).toLowerCase();if(/\b(pass|safe|verified|compliant|malicious|breach|compromised)\b/.test(forbidden))throw new Error('NEBULA_CANNOT_ASSERT_CONCLUSION')};
export function createConstellationStore(url?:string,now:()=>Date=()=>new Date()):ConstellationStore{return url?new PgStore(postgres(url,{prepare:false})):new MemoryStore(now)}
class MemoryStore implements ConstellationStore{
 constructor(private readonly now:()=>Date){}
 private entities=new Map<string,{org:string;v:Entity}>();private relationships:{org:string;v:Relationship}[]=[];private events:{org:string;v:ConstellationEvent}[]=[];
 async ready(){return true} async addEntity(org:string,input:Omit<Entity,'id'|'knownAt'>){assertEntitySemantics(input);const existing=[...this.entities.values()].find(x=>x.org===org&&x.v.entityType===input.entityType&&x.v.source===input.source&&x.v.identityKey===input.identityKey);if(existing)return structuredClone(existing.v);const v={id:randomUUID(),...input,firstObservedAt:iso(input.firstObservedAt),lastObservedAt:iso(input.lastObservedAt),knownAt:this.now().toISOString()};this.entities.set(v.id,{org,v});return structuredClone(v)}
 async addRelationship(org:string,input:Omit<Relationship,'id'|'knownAt'>){assertRelationshipSemantics(input);if(this.entities.get(input.fromEntityId)?.org!==org||this.entities.get(input.toEntityId)?.org!==org)return null;if(this.relationships.some(x=>x.org===org&&x.v.fromEntityId===input.fromEntityId&&x.v.toEntityId===input.toEntityId&&x.v.relationshipType===input.relationshipType&&x.v.evidenceHash===input.evidenceHash&&x.v.endedAt===null))return structuredClone(this.relationships.find(x=>x.org===org&&x.v.fromEntityId===input.fromEntityId&&x.v.toEntityId===input.toEntityId&&x.v.relationshipType===input.relationshipType&&x.v.evidenceHash===input.evidenceHash&&x.v.endedAt===null)!.v);const v={id:randomUUID(),...input,observedAt:iso(input.observedAt),endedAt:input.endedAt?iso(input.endedAt):null,knownAt:this.now().toISOString()};this.relationships.push({org,v});return structuredClone(v)}
 async addEvent(org:string,input:Omit<ConstellationEvent,'id'|'knownAt'>){assertEventSemantics(input);if(input.entityId&&this.entities.get(input.entityId)?.org!==org)return null;if(input.relationshipId&&!this.relationships.some(x=>x.org===org&&x.v.id===input.relationshipId))return null;const v={id:randomUUID(),...input,occurredAt:iso(input.occurredAt),knownAt:this.now().toISOString()};this.events.push({org,v});return structuredClone(v)}
 async snapshot(org:string,asOf:string,limit=500):Promise<Snapshot>{const t=Date.parse(asOf);const entities=[...this.entities.values()].filter(x=>x.org===org&&Date.parse(x.v.firstObservedAt)<=t&&Date.parse(x.v.knownAt??x.v.firstObservedAt)<=t).map(x=>x.v).slice(0,limit);const ids=new Set(entities.map(x=>x.id));const relationships=this.relationships.filter(x=>x.org===org&&Date.parse(x.v.observedAt)<=t&&Date.parse(x.v.knownAt??x.v.observedAt)<=t&&(!x.v.endedAt||Date.parse(x.v.endedAt)>t)&&ids.has(x.v.fromEntityId)&&ids.has(x.v.toEntityId)).map(x=>x.v).slice(0,limit);const relIds=new Set(relationships.map(x=>x.id));const events=this.events.filter(x=>x.org===org&&Date.parse(x.v.occurredAt)<=t&&Date.parse(x.v.knownAt??x.v.occurredAt)<=t&&(!x.v.entityId||ids.has(x.v.entityId))&&(!x.v.relationshipId||relIds.has(x.v.relationshipId))).map(x=>x.v).slice(0,limit);return{organizationId:org,asOf:iso(asOf),entities:structuredClone(entities),relationships:structuredClone(relationships),events:structuredClone(events),coverage:{state:entities.length?'OBSERVED':'UNKNOWN',note:entities.length?'Snapshot contains only persisted observations available by this timestamp.':'No persisted constellation evidence existed by this timestamp.'}}}
 async close(){this.entities.clear();this.relationships=[];this.events=[]}
}
type Row=Record<string,any>; const entity=(r:Row):Entity=>({id:r.id,identityKey:r.identity_key,entityType:r.entity_type,name:r.name,evidenceState:r.evidence_state,evidenceHash:r.evidence_hash,source:r.source,firstObservedAt:r.first_observed_at.toISOString(),lastObservedAt:r.last_observed_at.toISOString(),metadata:r.metadata??{},knownAt:r.known_at?.toISOString()??r.created_at?.toISOString()});
const relationship=(r:Row):Relationship=>({id:r.id,fromEntityId:r.from_entity_id,toEntityId:r.to_entity_id,relationshipType:r.relationship_type,evidenceState:r.evidence_state,evidenceHash:r.evidence_hash,source:r.source,observedAt:r.observed_at.toISOString(),endedAt:r.ended_at?.toISOString()??null,metadata:r.metadata??{},knownAt:r.known_at?.toISOString()??r.created_at?.toISOString()});
const event=(r:Row):ConstellationEvent=>({id:r.id,eventType:r.event_type,entityId:r.entity_id,relationshipId:r.relationship_id,evidenceState:r.evidence_state,summary:r.summary,evidenceHash:r.evidence_hash,source:r.source,occurredAt:r.occurred_at.toISOString(),metadata:r.metadata??{},knownAt:r.known_at?.toISOString()??r.created_at?.toISOString()});
class PgStore implements ConstellationStore{constructor(private sql:postgres.Sql){}
 async ready(){try{await this.sql`SELECT 1 FROM constellation_entities LIMIT 0`;return true}catch{return false}}
 async addEntity(org:string,i:Omit<Entity,'id'|'knownAt'>){assertEntitySemantics(i);const existing=await this.sql<Row[]>`SELECT * FROM constellation_entities WHERE organization_id=${org} AND entity_type=${i.entityType} AND source=${i.source} AND identity_key=${i.identityKey} LIMIT 1`;if(existing[0])return entity(existing[0]);const r=await this.sql<Row[]>`INSERT INTO constellation_entities(id,organization_id,identity_key,entity_type,name,evidence_state,evidence_hash,source,first_observed_at,last_observed_at,metadata) VALUES(${randomUUID()},${org},${i.identityKey},${i.entityType},${i.name},${i.evidenceState},${i.evidenceHash},${i.source},${i.firstObservedAt},${i.lastObservedAt},${JSON.stringify(i.metadata)}) RETURNING *`;if(!r[0])throw new Error('ENTITY_INSERT_FAILED');return entity(r[0])}
 async addRelationship(org:string,i:Omit<Relationship,'id'|'knownAt'>){assertRelationshipSemantics(i);const existing=await this.sql<Row[]>`SELECT * FROM constellation_relationships WHERE organization_id=${org} AND from_entity_id=${i.fromEntityId} AND to_entity_id=${i.toEntityId} AND relationship_type=${i.relationshipType} AND evidence_hash=${i.evidenceHash} AND ended_at IS NULL ORDER BY known_at DESC LIMIT 1`;if(existing[0])return relationship(existing[0]);const r=await this.sql<Row[]>`INSERT INTO constellation_relationships(id,organization_id,from_entity_id,to_entity_id,relationship_type,evidence_state,evidence_hash,source,observed_at,ended_at,metadata) SELECT ${randomUUID()},${org},${i.fromEntityId},${i.toEntityId},${i.relationshipType},${i.evidenceState},${i.evidenceHash},${i.source},${i.observedAt},${i.endedAt},${JSON.stringify(i.metadata)} WHERE EXISTS(SELECT 1 FROM constellation_entities WHERE organization_id=${org} AND id=${i.fromEntityId}) AND EXISTS(SELECT 1 FROM constellation_entities WHERE organization_id=${org} AND id=${i.toEntityId}) RETURNING *`;return r[0]?relationship(r[0]):null}
 async addEvent(org:string,i:Omit<ConstellationEvent,'id'|'knownAt'>){assertEventSemantics(i);const r=await this.sql<Row[]>`INSERT INTO constellation_events(id,organization_id,event_type,entity_id,relationship_id,evidence_state,summary,evidence_hash,source,occurred_at,metadata) SELECT ${randomUUID()},${org},${i.eventType},${i.entityId},${i.relationshipId},${i.evidenceState},${i.summary},${i.evidenceHash},${i.source},${i.occurredAt},${JSON.stringify(i.metadata)} WHERE (${i.entityId}::uuid IS NULL OR EXISTS(SELECT 1 FROM constellation_entities WHERE organization_id=${org} AND id=${i.entityId})) AND (${i.relationshipId}::uuid IS NULL OR EXISTS(SELECT 1 FROM constellation_relationships WHERE organization_id=${org} AND id=${i.relationshipId})) RETURNING *`;return r[0]?event(r[0]):null}
 async snapshot(org:string,asOf:string,limit=500){const es=(await this.sql<Row[]>`SELECT * FROM constellation_entities WHERE organization_id=${org} AND first_observed_at<=${asOf} AND known_at<=${asOf} ORDER BY first_observed_at,id LIMIT ${limit}`).map(entity);const ids=es.map(x=>x.id);if(!ids.length)return{organizationId:org,asOf:iso(asOf),entities:[],relationships:[],events:[],coverage:{state:'UNKNOWN' as const,note:'No persisted constellation evidence existed by this timestamp.'}};const rs=(await this.sql<Row[]>`SELECT * FROM constellation_relationships WHERE organization_id=${org} AND observed_at<=${asOf} AND known_at<=${asOf} AND (ended_at IS NULL OR ended_at>${asOf}) AND from_entity_id=ANY(${ids}::uuid[]) AND to_entity_id=ANY(${ids}::uuid[]) ORDER BY observed_at,id LIMIT ${limit}`).map(relationship);const relIds=rs.map(x=>x.id);const ev=(await this.sql<Row[]>`SELECT * FROM constellation_events WHERE organization_id=${org} AND occurred_at<=${asOf} AND known_at<=${asOf} AND (entity_id IS NULL OR entity_id=ANY(${ids}::uuid[])) AND (relationship_id IS NULL OR relationship_id=ANY(${relIds}::uuid[])) ORDER BY occurred_at,id LIMIT ${limit}`).map(event);return{organizationId:org,asOf:iso(asOf),entities:es,relationships:rs,events:ev,coverage:{state:'OBSERVED' as const,note:'Snapshot contains only persisted observations available by this timestamp.'}}}
 async close(){await this.sql.end({timeout:5})}
}