import postgres from 'postgres';
import { randomUUID } from 'node:crypto';
export type EntityType='AI_AGENT'|'MODEL'|'HUMAN'|'TOOL'|'API'|'DATABASE'|'OBSERVER'|'POLICY'|'SYSTEM'|'WORKLOAD'|'CREDENTIAL'|'ARTIFACT'|'UNKNOWN';
export type EvidenceState='OBSERVED'|'VERIFIED'|'DECLARED'|'UNKNOWN'|'STALE'|'CONFLICTING'|'UNAVAILABLE';
export type RelationshipType='ORBIT'|'CLUSTER'|'WORMHOLE'|'DEPENDENCY'|'INTERACTION'|'PROVENANCE'|'OBSERVATION'|'POLICY_APPLIES'|'TRANSIENT';
export type ConstellationEventType='SUPERNOVA'|'BLACK_HOLE'|'NEBULA'|'CHANGE'|'BOUNDARY'|'VISIBILITY_LOSS';
export interface Entity{id:string;entityType:EntityType;name:string;evidenceState:EvidenceState;evidenceHash:string;source:string;firstObservedAt:string;lastObservedAt:string;metadata:Record<string,unknown>;knownAt?:string}
export interface Relationship{id:string;fromEntityId:string;toEntityId:string;relationshipType:RelationshipType;evidenceState:EvidenceState;evidenceHash:string;source:string;observedAt:string;endedAt:string|null;metadata:Record<string,unknown>;knownAt?:string}
export interface ConstellationEvent{id:string;eventType:ConstellationEventType;entityId:string|null;relationshipId:string|null;evidenceState:EvidenceState;summary:string;evidenceHash:string;source:string;occurredAt:string;metadata:Record<string,unknown>;knownAt?:string}
export interface Snapshot{asOf:string;entities:Entity[];relationships:Relationship[];events:ConstellationEvent[];coverage:{state:'OBSERVED'|'UNKNOWN';note:string}}
export interface ConstellationStore{ready():Promise<boolean>;addEntity(org:string,input:Omit<Entity,'id'>):Promise<Entity>;addRelationship(org:string,input:Omit<Relationship,'id'>):Promise<Relationship|null>;addEvent(org:string,input:Omit<ConstellationEvent,'id'>):Promise<ConstellationEvent|null>;snapshot(org:string,asOf:string,limit?:number):Promise<Snapshot>;close():Promise<void>}
const validHash=(x:string)=>/^[a-f0-9]{64}$/.test(x);
const iso=(x:string)=>new Date(x).toISOString();
export function createConstellationStore(url?:string):ConstellationStore{return url?new PgStore(postgres(url,{prepare:false})):new MemoryStore()}
class MemoryStore implements ConstellationStore{
 private entities=new Map<string,{org:string;v:Entity}>();private relationships:{org:string;v:Relationship}[]=[];private events:{org:string;v:ConstellationEvent}[]=[];
 async ready(){return true} async addEntity(org:string,input:Omit<Entity,'id'>){if(!validHash(input.evidenceHash))throw new Error('INVALID_EVIDENCE_HASH');const v={id:randomUUID(),...input,firstObservedAt:iso(input.firstObservedAt),lastObservedAt:iso(input.lastObservedAt)};this.entities.set(v.id,{org,v});return structuredClone(v)}
 async addRelationship(org:string,input:Omit<Relationship,'id'>){if(!validHash(input.evidenceHash))throw new Error('INVALID_EVIDENCE_HASH');if(this.entities.get(input.fromEntityId)?.org!==org||this.entities.get(input.toEntityId)?.org!==org)return null;const v={id:randomUUID(),...input,observedAt:iso(input.observedAt),endedAt:input.endedAt?iso(input.endedAt):null};this.relationships.push({org,v});return structuredClone(v)}
 async addEvent(org:string,input:Omit<ConstellationEvent,'id'>){if(!validHash(input.evidenceHash))throw new Error('INVALID_EVIDENCE_HASH');if(input.entityId&&this.entities.get(input.entityId)?.org!==org)return null;if(input.relationshipId&&!this.relationships.some(x=>x.org===org&&x.v.id===input.relationshipId))return null;const v={id:randomUUID(),...input,occurredAt:iso(input.occurredAt)};this.events.push({org,v});return structuredClone(v)}
 async snapshot(org:string,asOf:string,limit=500):Promise<Snapshot>{const t=Date.parse(asOf);const entities=[...this.entities.values()].filter(x=>x.org===org&&Date.parse(x.v.firstObservedAt)<=t&&Date.parse(x.v.knownAt??x.v.firstObservedAt)<=t).map(x=>x.v).slice(0,limit);const ids=new Set(entities.map(x=>x.id));const relationships=this.relationships.filter(x=>x.org===org&&Date.parse(x.v.observedAt)<=t&&Date.parse(x.v.knownAt??x.v.observedAt)<=t&&(!x.v.endedAt||Date.parse(x.v.endedAt)>t)&&ids.has(x.v.fromEntityId)&&ids.has(x.v.toEntityId)).map(x=>x.v).slice(0,limit);const relIds=new Set(relationships.map(x=>x.id));const events=this.events.filter(x=>x.org===org&&Date.parse(x.v.occurredAt)<=t&&Date.parse(x.v.knownAt??x.v.occurredAt)<=t&&(!x.v.entityId||ids.has(x.v.entityId))&&(!x.v.relationshipId||relIds.has(x.v.relationshipId))).map(x=>x.v).slice(0,limit);return{asOf:iso(asOf),entities:structuredClone(entities),relationships:structuredClone(relationships),events:structuredClone(events),coverage:{state:entities.length?'OBSERVED':'UNKNOWN',note:entities.length?'Snapshot contains only persisted observations available by this timestamp.':'No persisted constellation evidence existed by this timestamp.'}}}
 async close(){this.entities.clear();this.relationships=[];this.events=[]}
}
type Row=Record<string,any>; const entity=(r:Row):Entity=>({id:r.id,entityType:r.entity_type,name:r.name,evidenceState:r.evidence_state,evidenceHash:r.evidence_hash,source:r.source,firstObservedAt:r.first_observed_at.toISOString(),lastObservedAt:r.last_observed_at.toISOString(),metadata:r.metadata??{},knownAt:r.known_at?.toISOString()??r.created_at?.toISOString()});
const relationship=(r:Row):Relationship=>({id:r.id,fromEntityId:r.from_entity_id,toEntityId:r.to_entity_id,relationshipType:r.relationship_type,evidenceState:r.evidence_state,evidenceHash:r.evidence_hash,source:r.source,observedAt:r.observed_at.toISOString(),endedAt:r.ended_at?.toISOString()??null,metadata:r.metadata??{},knownAt:r.known_at?.toISOString()??r.created_at?.toISOString()});
const event=(r:Row):ConstellationEvent=>({id:r.id,eventType:r.event_type,entityId:r.entity_id,relationshipId:r.relationship_id,evidenceState:r.evidence_state,summary:r.summary,evidenceHash:r.evidence_hash,source:r.source,occurredAt:r.occurred_at.toISOString(),metadata:r.metadata??{},knownAt:r.known_at?.toISOString()??r.created_at?.toISOString()});
class PgStore implements ConstellationStore{constructor(private sql:postgres.Sql){}
 async ready(){try{await this.sql`SELECT 1 FROM constellation_entities LIMIT 0`;return true}catch{return false}}
 async addEntity(org:string,i:Omit<Entity,'id'>){const r=await this.sql<Row[]>`INSERT INTO constellation_entities(id,organization_id,entity_type,name,evidence_state,evidence_hash,source,first_observed_at,last_observed_at,metadata) VALUES(${randomUUID()},${org},${i.entityType},${i.name},${i.evidenceState},${i.evidenceHash},${i.source},${i.firstObservedAt},${i.lastObservedAt},${JSON.stringify(i.metadata)}) RETURNING *`;if(!r[0])throw new Error('ENTITY_INSERT_FAILED');return entity(r[0])}
 async addRelationship(org:string,i:Omit<Relationship,'id'>){const r=await this.sql<Row[]>`INSERT INTO constellation_relationships(id,organization_id,from_entity_id,to_entity_id,relationship_type,evidence_state,evidence_hash,source,observed_at,ended_at,metadata) SELECT ${randomUUID()},${org},${i.fromEntityId},${i.toEntityId},${i.relationshipType},${i.evidenceState},${i.evidenceHash},${i.source},${i.observedAt},${i.endedAt},${JSON.stringify(i.metadata)} WHERE EXISTS(SELECT 1 FROM constellation_entities WHERE organization_id=${org} AND id=${i.fromEntityId}) AND EXISTS(SELECT 1 FROM constellation_entities WHERE organization_id=${org} AND id=${i.toEntityId}) RETURNING *`;return r[0]?relationship(r[0]):null}
 async addEvent(org:string,i:Omit<ConstellationEvent,'id'>){const r=await this.sql<Row[]>`INSERT INTO constellation_events(id,organization_id,event_type,entity_id,relationship_id,evidence_state,summary,evidence_hash,source,occurred_at,metadata) SELECT ${randomUUID()},${org},${i.eventType},${i.entityId},${i.relationshipId},${i.evidenceState},${i.summary},${i.evidenceHash},${i.source},${i.occurredAt},${JSON.stringify(i.metadata)} WHERE (${i.entityId}::uuid IS NULL OR EXISTS(SELECT 1 FROM constellation_entities WHERE organization_id=${org} AND id=${i.entityId})) AND (${i.relationshipId}::uuid IS NULL OR EXISTS(SELECT 1 FROM constellation_relationships WHERE organization_id=${org} AND id=${i.relationshipId})) RETURNING *`;return r[0]?event(r[0]):null}
 async snapshot(org:string,asOf:string,limit=500){const es=(await this.sql<Row[]>`SELECT * FROM constellation_entities WHERE organization_id=${org} AND first_observed_at<=${asOf} AND known_at<=${asOf} AND known_at<=${asOf} ORDER BY first_observed_at,id LIMIT ${limit}`).map(entity);const ids=es.map(x=>x.id);if(!ids.length)return{asOf:iso(asOf),entities:[],relationships:[],events:[],coverage:{state:'UNKNOWN' as const,note:'No persisted constellation evidence existed by this timestamp.'}};const rs=(await this.sql<Row[]>`SELECT * FROM constellation_relationships WHERE organization_id=${org} AND observed_at<=${asOf} AND (ended_at IS NULL OR ended_at>${asOf}) AND from_entity_id=ANY(${ids}::uuid[]) AND to_entity_id=ANY(${ids}::uuid[]) ORDER BY observed_at,id LIMIT ${limit}`).map(relationship);const ev=(await this.sql<Row[]>`SELECT * FROM constellation_events WHERE organization_id=${org} AND occurred_at<=${asOf} AND known_at<=${asOf} ORDER BY occurred_at,id LIMIT ${limit}`).map(event);return{asOf:iso(asOf),entities:es,relationships:rs,events:ev,coverage:{state:'OBSERVED' as const,note:'Snapshot contains only persisted observations available by this timestamp.'}}}
 async close(){await this.sql.end({timeout:5})}
}