import postgres from 'postgres';
import { createHash } from 'node:crypto';
import { nanoid } from 'nanoid';
import type { VerificationRecord } from './domain/media.js';
export type ApiRole = 'viewer' | 'creator' | 'reviewer' | 'moderator' | 'analyst' | 'organization_admin' | 'platform_admin' | 'super_admin';
export interface ApiIdentity { keyId: string; organizationId: string | null; role: ApiRole; }
export interface RecordStore { save(record: VerificationRecord): Promise<void>; get(id: string, organizationId?: string): Promise<VerificationRecord | null>; ready(): Promise<boolean>; tenantIsolationRoleSafe(): Promise<boolean>; authenticateApiKey(key: string): Promise<ApiIdentity | null>; createOrganization(name: string): Promise<{ id: string; name: string }>; createApiKey(organizationId: string, name: string, role: ApiRole, expiresAt?: string | null, rotatedFromId?: string | null): Promise<{ id: string; key: string; expiresAt: string | null }>; revokeApiKey(organizationId:string,keyId:string):Promise<boolean>; rotateApiKey(organizationId:string,keyId:string,name:string,role:ApiRole,expiresAt?:string|null):Promise<{id:string;key:string;expiresAt:string|null}|null>; listApiKeys(organizationId:string):Promise<Array<{id:string;name:string;role:ApiRole;createdAt:string;lastUsedAt:string|null;expiresAt:string|null;revokedAt:string|null}>>; createAppeal(organizationId:string,passportId:string,reason:string,evidence:string[]):Promise<{id:string}>; createReport(organizationId:string,passportId:string,category:string,description:string):Promise<{id:string}>; beginProcessing(organizationId:string,idempotencyKey:string,contentHash:string):Promise<{id:string;stage:string;assetId:string|null;attemptCount:number}>; markProcessing(id:string,organizationId:string,stage:'QUARANTINED'|'BLOCKED_UNVERIFIED'|'SCANNED_CLEAN'|'VERIFIED'|'PERSISTED'|'COMPLETED'|'FAILED',assetId?:string,failureCode?:string):Promise<void>; close(): Promise<void>; }
const hashKey = (key: string) => createHash('sha256').update(key).digest('hex');
export function createStore(databaseUrl: string | undefined, options: { max?:number; idleTimeoutSeconds?:number; connectTimeoutSeconds?:number; statementTimeoutMs?:number; idleTransactionTimeoutMs?:number } = {}): RecordStore { if (!databaseUrl) return new MemoryStore(); const sql = postgres(databaseUrl, { max: options.max ?? 10, idle_timeout: options.idleTimeoutSeconds ?? 20, connect_timeout: options.connectTimeoutSeconds ?? 10, prepare: false, onnotice: () => undefined, connection: { statement_timeout: String(options.statementTimeoutMs ?? 30000), idle_in_transaction_session_timeout: String(options.idleTransactionTimeoutMs ?? 60000) } }); return new PostgresStore(sql); }
class MemoryStore implements RecordStore {
  private readonly records = new Map<string, VerificationRecord>(); private readonly processing = new Map<string,{id:string;organizationId:string;contentHash:string;stage:string;assetId:string|null;attemptCount:number}>(); private readonly keys = new Map<string, ApiIdentity & { name?:string; createdAt?:string; lastUsedAt?:string|null; expiresAt?:string|null; revokedAt?:string|null }>();
  async save(record: VerificationRecord) { this.records.set(record.asset.id, structuredClone(record)); }
  async get(id: string, organizationId?: string) { const r=this.records.get(id); if(!r || (organizationId && r.asset.organizationId!==organizationId)) return null; return structuredClone(r); }
  async ready() { return true; }
  async tenantIsolationRoleSafe() { return true; }
  async authenticateApiKey(key: string) { const v=this.keys.get(hashKey(key)); if(!v||v.revokedAt||(v.expiresAt&&Date.parse(v.expiresAt)<=Date.now()))return null;v.lastUsedAt=new Date().toISOString();return {keyId:v.keyId,organizationId:v.organizationId,role:v.role}; }
  async createOrganization(name: string) { return { id: nanoid(21), name }; }
  async createApiKey(organizationId:string,name:string,role:ApiRole,expiresAt:string|null=null,_rotatedFromId:string|null=null){const key=`mp_${nanoid(32)}`;const id=nanoid(21);this.keys.set(hashKey(key),{keyId:id,organizationId,role,name,createdAt:new Date().toISOString(),lastUsedAt:null,expiresAt,revokedAt:null});return{id,key,expiresAt}} async revokeApiKey(organizationId:string,keyId:string){for(const v of this.keys.values())if(v.keyId===keyId&&v.organizationId===organizationId&&!v.revokedAt){v.revokedAt=new Date().toISOString();return true}return false} async rotateApiKey(organizationId:string,keyId:string,name:string,role:ApiRole,expiresAt:string|null=null){const ok=await this.revokeApiKey(organizationId,keyId);if(!ok)return null;return this.createApiKey(organizationId,name,role,expiresAt,keyId)} async listApiKeys(organizationId:string){return [...this.keys.values()].filter(v=>v.organizationId===organizationId).map(v=>({id:v.keyId,name:v.name||'key',role:v.role,createdAt:v.createdAt||new Date(0).toISOString(),lastUsedAt:v.lastUsedAt||null,expiresAt:v.expiresAt||null,revokedAt:v.revokedAt||null}))}
  async beginProcessing(organizationId:string,idempotencyKey:string,contentHash:string){const k=organizationId+'\0'+idempotencyKey;const old=this.processing.get(k);if(old){if(old.contentHash!==contentHash)throw Error('IDEMPOTENCY_KEY_CONTENT_MISMATCH');old.attemptCount++;return structuredClone(old)}const v={id:nanoid(21),organizationId,contentHash,stage:'QUARANTINED',assetId:null,attemptCount:1};this.processing.set(k,v);return structuredClone(v)} async markProcessing(id:string,organizationId:string,stage:'QUARANTINED'|'BLOCKED_UNVERIFIED'|'SCANNED_CLEAN'|'VERIFIED'|'PERSISTED'|'COMPLETED'|'FAILED',assetId?:string,_failureCode?:string){for(const v of this.processing.values())if(v.id===id&&v.organizationId===organizationId){v.stage=stage;if(assetId)v.assetId=assetId;return}throw Error('PROCESSING_RUN_NOT_FOUND')} async createAppeal(organizationId:string,passportId:string,_reason:string,_evidence:string[]){const r=this.records.get(passportId);if(!r||r.asset.organizationId!==organizationId)throw Error('NOT_FOUND');return{id:nanoid(21)}} async createReport(organizationId:string,passportId:string,_category:string,_description:string){const r=this.records.get(passportId);if(!r||r.asset.organizationId!==organizationId)throw Error('NOT_FOUND');return{id:nanoid(21)}} async close() { this.records.clear(); this.keys.clear(); }
}
class PostgresStore implements RecordStore {
  constructor(private readonly sql: postgres.Sql) {}
  async save(record: VerificationRecord) {
    await this.sql.begin(async (tx) => {
      
      await tx`INSERT INTO media_assets (id, sha256, mime, kind, size_bytes, original_filename, declared_ai_use, organization_id, creator_id) VALUES (${record.asset.id}, ${record.asset.sha256}, ${record.asset.mime}, ${record.asset.kind}, ${record.asset.sizeBytes}, ${record.asset.originalFilename}, ${record.asset.declaredAiUse ?? 'UNKNOWN'}, ${record.asset.organizationId ?? null}, ${record.asset.creatorId ?? null}) ON CONFLICT (id) DO UPDATE SET declared_ai_use=EXCLUDED.declared_ai_use`;
      await tx`INSERT INTO media_verifications (id, organization_id, sha256, mime, kind, size_bytes, original_filename, record_json) VALUES (${record.asset.id}, ${record.asset.organizationId ?? null}, ${record.asset.sha256}, ${record.asset.mime}, ${record.asset.kind}, ${record.asset.sizeBytes}, ${record.asset.originalFilename}, ${JSON.stringify(record)}) ON CONFLICT (id) DO UPDATE SET record_json = EXCLUDED.record_json, organization_id=EXCLUDED.organization_id`;
      if(record.asset.organizationId){ const rh=createHash('sha256').update(JSON.stringify(record)).digest('hex'); await tx`INSERT INTO media_verification_history(id,organization_id,asset_id,record_json,record_hash) VALUES(${nanoid(21)},${record.asset.organizationId},${record.asset.id},${JSON.stringify(record)},${rh}) ON CONFLICT(organization_id,asset_id,record_hash) DO NOTHING`; }
      await tx`INSERT INTO media_passports (id, asset_id, trust_score, confidence, decision, ai_status, created_at, updated_at) VALUES (${record.asset.id}, ${record.asset.id}, ${record.trustScore}, ${record.confidence}, ${record.decision}, ${record.aiStatus}, ${record.createdAt ? new Date(record.createdAt) : new Date()}, now()) ON CONFLICT (id) DO UPDATE SET trust_score=EXCLUDED.trust_score, confidence=EXCLUDED.confidence, decision=EXCLUDED.decision, ai_status=EXCLUDED.ai_status, updated_at=now()`;
      for (const [dimension, score] of Object.entries(record.trustVector)) await tx`INSERT INTO trust_observations (id, passport_id, dimension, score, confidence, model_name, model_version, content_hash, policy_version, observed_at) VALUES (${nanoid(21)}, ${record.asset.id}, ${dimension}, ${score}, ${record.confidence}, 'media-passport-engine', '1.0.0', ${record.asset.sha256}, ${record.policyVersion}, now()) ON CONFLICT DO NOTHING`;
      for (const observation of record.observations) { const evidenceId = observation.id ?? nanoid(21); await tx`INSERT INTO evidence (id, passport_id, source, evidence_type, result, confidence, details, content_hash, model_name, model_version, created_at) VALUES (${evidenceId}, ${record.asset.id}, ${observation.source}, ${observation.signal}, ${observation.result}, ${observation.confidence ?? null}, ${JSON.stringify({ details: observation.details ?? null })}, ${observation.contentHash ?? record.asset.sha256}, ${observation.model?.name ?? 'media-passport-engine'}, ${observation.model?.version ?? '1.0.0'}, ${observation.createdAt ? new Date(observation.createdAt) : new Date()})`; }
      await tx`INSERT INTO provenance_manifests (id, passport_id, status, issuer, manifest_hash, assertions, created_at) VALUES (${nanoid(21)}, ${record.asset.id}, ${record.provenance.status}, ${record.provenance.issuer ?? null}, ${record.provenance.manifestHash ?? null}, ${JSON.stringify(record.provenance.activeManifest ?? [])}, now())`;
    });
  }
  async get(id: string, organizationId?: string) { const rows = organizationId ? await this.sql<{ record_json: VerificationRecord }[]>`SELECT record_json FROM media_verifications WHERE id=${id} AND organization_id=${organizationId} LIMIT 1` : await this.sql<{ record_json: VerificationRecord }[]>`SELECT record_json FROM media_verifications WHERE id=${id} LIMIT 1`; return rows[0]?.record_json ?? null; }
  async ready() { try { await this.sql`SELECT 1`; return true; } catch { return false; } }
  async tenantIsolationRoleSafe() {
    try {
      const rows=await this.sql<{safe:boolean}[]>`SELECT (NOT rolsuper AND NOT rolbypassrls) AS safe FROM pg_roles WHERE rolname=current_user`;
      return rows[0]?.safe===true;
    } catch { return false; }
  }
  async authenticateApiKey(key: string) { const rows = await this.sql<{ id: string; organization_id: string; role: ApiRole }[]>`SELECT id, organization_id, role FROM api_keys WHERE key_hash = ${hashKey(key)} AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now()) LIMIT 1`; if (!rows[0]) return null; await this.sql`UPDATE api_keys SET last_used_at=now() WHERE id=${rows[0].id}`; return { keyId: rows[0].id, organizationId: rows[0].organization_id, role: rows[0].role }; }
  async createOrganization(name: string) { const id = nanoid(21); await this.sql`INSERT INTO organizations (id, name) VALUES (${id}, ${name})`; return { id, name }; }
  async createApiKey(organizationId:string,name:string,role:ApiRole,expiresAt:string|null=null,rotatedFromId:string|null=null){const key=`mp_${nanoid(32)}`;const id=nanoid(21);await this.sql`INSERT INTO api_keys(id,organization_id,key_hash,name,role,expires_at,rotated_from_id) VALUES(${id},${organizationId},${hashKey(key)},${name},${role},${expiresAt?new Date(expiresAt):null},${rotatedFromId})`;return{id,key,expiresAt}} async revokeApiKey(organizationId:string,keyId:string){const r=await this.sql`UPDATE api_keys SET revoked_at=now() WHERE id=${keyId} AND organization_id=${organizationId} AND revoked_at IS NULL RETURNING id`;return r.length===1} async rotateApiKey(organizationId:string,keyId:string,name:string,role:ApiRole,expiresAt:string|null=null){return this.sql.begin(async tx=>{const old=await tx`UPDATE api_keys SET revoked_at=now() WHERE id=${keyId} AND organization_id=${organizationId} AND revoked_at IS NULL RETURNING id`;if(!old.length)return null;const key=`mp_${nanoid(32)}`;const id=nanoid(21);await tx`INSERT INTO api_keys(id,organization_id,key_hash,name,role,expires_at,rotated_from_id) VALUES(${id},${organizationId},${hashKey(key)},${name},${role},${expiresAt?new Date(expiresAt):null},${keyId})`;return{id,key,expiresAt}})} async listApiKeys(organizationId:string){const r=await this.sql<any[]>`SELECT id,name,role,created_at,last_used_at,expires_at,revoked_at FROM api_keys WHERE organization_id=${organizationId} ORDER BY created_at DESC`;return r.map(x=>({id:x.id,name:x.name,role:x.role,createdAt:new Date(x.created_at).toISOString(),lastUsedAt:x.last_used_at?new Date(x.last_used_at).toISOString():null,expiresAt:x.expires_at?new Date(x.expires_at).toISOString():null,revokedAt:x.revoked_at?new Date(x.revoked_at).toISOString():null}))}
  async beginProcessing(organizationId:string,idempotencyKey:string,contentHash:string){const id=nanoid(21);const r=await this.sql`INSERT INTO media_processing_runs(id,organization_id,content_hash,idempotency_key,stage) VALUES(${id},${organizationId},${contentHash},${idempotencyKey},'QUARANTINED') ON CONFLICT(organization_id,idempotency_key) DO UPDATE SET attempt_count=media_processing_runs.attempt_count+1,updated_at=now() RETURNING id,stage,asset_id,attempt_count,content_hash`;const x=r[0] as any;if(x.content_hash&&x.content_hash!==contentHash)throw Error('IDEMPOTENCY_KEY_CONTENT_MISMATCH');return{id:x.id,stage:x.stage,assetId:x.asset_id??null,attemptCount:x.attempt_count}} async markProcessing(id:string,organizationId:string,stage:'QUARANTINED'|'SCANNED_CLEAN'|'VERIFIED'|'PERSISTED'|'COMPLETED'|'FAILED',assetId?:string,failureCode?:string){await this.sql`UPDATE media_processing_runs SET stage=${stage},asset_id=COALESCE(${assetId??null},asset_id),failure_code=${failureCode??null},updated_at=now() WHERE id=${id} AND organization_id=${organizationId}`} async createAppeal(organizationId:string,passportId:string,reason:string,evidence:string[]){const id=nanoid(21);const r=await this.sql`INSERT INTO appeals(id,passport_id,reason,submitted_evidence,status) SELECT ${id},p.id,${reason},${JSON.stringify(evidence)},'human_review' FROM media_passports p JOIN media_assets a ON a.id=p.asset_id WHERE p.id=${passportId} AND a.organization_id=${organizationId} RETURNING id`;if(!r.length)throw Error('NOT_FOUND');return{id}} async createReport(organizationId:string,passportId:string,category:string,description:string){const id=nanoid(21);const r=await this.sql`INSERT INTO reports(id,passport_id,category,description,status) SELECT ${id},p.id,${category},${description},'open' FROM media_passports p JOIN media_assets a ON a.id=p.asset_id WHERE p.id=${passportId} AND a.organization_id=${organizationId} RETURNING id`;if(!r.length)throw Error('NOT_FOUND');return{id}} async close() { await this.sql.end({ timeout: 5 }); }
}
