import postgres from 'postgres';
import { createHash, randomUUID } from 'node:crypto';

export type AccountabilityDecision='ALLOW'|'FLAG'|'REQUIRE_HUMAN'|'BLOCK';
export type DecisionMode='POLICY'|'BOUNDARY'|'RISK_SIGNAL'|'HUMAN'|'COMBINED';
export type HumanState='NOT_REQUIRED'|'PENDING'|'APPROVED'|'DENIED';
export type OutcomeState='UNKNOWN'|'VERIFIED'|'FAILED'|'UNAVAILABLE'|'CONFLICTING';
export interface DecisionRecord { id:string; organizationId:string; aiId:string; actionEventId:string|null; decision:AccountabilityDecision; decisionMode:DecisionMode; reason:string; policyId:string|null; policyVersion:string|null; boundaryId:string|null; boundaryVersion:string|null; evidenceSnapshot:string[]; riskSignals:string[]; humanState:HumanState; humanActor:string|null; decidedAt:string; outcomeEventId:string|null; outcomeState:OutcomeState; previousHash:string|null; decisionHash:string; createdAt:string }
export type DecisionInput=Omit<DecisionRecord,'id'|'organizationId'|'previousHash'|'decisionHash'|'createdAt'|'outcomeEventId'|'outcomeState'>;
export interface DecisionStore { append(org:string,input:DecisionInput):Promise<DecisionRecord>; timeline(org:string,aiId:string):Promise<DecisionRecord[]>; close():Promise<void> }
const digest=(v:string)=>createHash('sha256').update(v).digest('hex');
function make(org:string,input:DecisionInput,previousHash:string|null):DecisionRecord { const base={id:randomUUID(),organizationId:org,...input,decidedAt:new Date(input.decidedAt).toISOString(),outcomeEventId:null,outcomeState:'UNKNOWN' as const,previousHash,createdAt:new Date().toISOString()};return {...base,decisionHash:digest(JSON.stringify(base))}; }
export function createDecisionStore(url?:string):DecisionStore{return url?new PgDecisionStore(postgres(url,{prepare:false})):new MemoryDecisionStore();}
class MemoryDecisionStore implements DecisionStore { private rows=new Map<string,DecisionRecord[]>();async append(org:string,input:DecisionInput){const key=org+':'+input.aiId,rows=this.rows.get(key)??[],r=make(org,input,rows.at(-1)?.decisionHash??null);rows.push(r);this.rows.set(key,rows);return structuredClone(r);}async timeline(org:string,aiId:string){return structuredClone(this.rows.get(org+':'+aiId)??[]);}async close(){this.rows.clear();}}
class PgDecisionStore implements DecisionStore {
 constructor(private sql:postgres.Sql){}
 async append(org:string,input:DecisionInput){return this.sql.begin(async tx=>{const ai=await tx`SELECT id FROM ai_identities WHERE organization_id=${org} AND id=${input.aiId} FOR UPDATE`;if(!ai.length)throw new Error('AI_NOT_FOUND');if(input.actionEventId){const event=await tx`SELECT id FROM flight_records WHERE organization_id=${org} AND ai_identity_id=${input.aiId} AND id=${input.actionEventId}`;if(!event.length)throw new Error('ACTION_EVENT_NOT_FOUND');}const prior=await tx<{decision_hash:string}[]>`SELECT decision_hash FROM accountability_decisions WHERE organization_id=${org} AND ai_identity_id=${input.aiId} ORDER BY decided_at DESC,id DESC LIMIT 1`;const r=make(org,input,prior[0]?.decision_hash??null);await tx`INSERT INTO accountability_decisions(id,organization_id,ai_identity_id,action_event_id,decision,decision_mode,reason,policy_id,policy_version,boundary_id,boundary_version,evidence_snapshot,risk_signals,human_state,human_actor,decided_at,outcome_event_id,outcome_state,previous_hash,decision_hash,created_at) VALUES (${r.id},${org},${r.aiId},${r.actionEventId},${r.decision},${r.decisionMode},${r.reason},${r.policyId},${r.policyVersion},${r.boundaryId},${r.boundaryVersion},${this.sql.json(r.evidenceSnapshot)},${this.sql.json(r.riskSignals)},${r.humanState},${r.humanActor},${r.decidedAt},NULL,'UNKNOWN',${r.previousHash},${r.decisionHash},${r.createdAt})`;return r;});}
 async timeline(org:string,aiId:string){const rows=await this.sql<any[]>`SELECT * FROM accountability_decisions WHERE organization_id=${org} AND ai_identity_id=${aiId} ORDER BY decided_at ASC,id ASC`;return rows.map(r=>({id:r.id,organizationId:r.organization_id,aiId:r.ai_identity_id,actionEventId:r.action_event_id,decision:r.decision,decisionMode:r.decision_mode,reason:r.reason,policyId:r.policy_id,policyVersion:r.policy_version,boundaryId:r.boundary_id,boundaryVersion:r.boundary_version,evidenceSnapshot:r.evidence_snapshot,riskSignals:r.risk_signals,humanState:r.human_state,humanActor:r.human_actor,decidedAt:r.decided_at.toISOString(),outcomeEventId:r.outcome_event_id,outcomeState:r.outcome_state,previousHash:r.previous_hash,decisionHash:r.decision_hash,createdAt:r.created_at.toISOString()}));}
 async close(){await this.sql.end({timeout:5});}
}
