import{createHash,randomUUID}from'node:crypto';import type{KernelStore}from'./evidence-store.js';
export type EnforcementDecision='ALLOW'|'BLOCK';export type EnforcementOutcome='ALLOWED'|'BLOCKED'|'FAILED'|'UNAVAILABLE'|'UNKNOWN';
export interface EnforcementAttempt{id:string;organizationId:string;policyEvaluationId:string;subjectType:string;subjectId:string;actionType:string;targetReference:string|null;enforcementPoint:string;decision:EnforcementDecision;outcome:EnforcementOutcome;attemptedAt:string;completedAt:string|null;evidenceId:string|null;evidenceHash:string|null;preventionState:'PREVENTED'|'NOT_PREVENTED'|'UNKNOWN'|'UNAVAILABLE';receiptDigest:string}
const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
const seal=(x:Omit<EnforcementAttempt,'receiptDigest'>):EnforcementAttempt=>({...x,receiptDigest:hash(JSON.stringify(x))});
export async function verifiedEnforcement(input:{organizationId:string;policyEvaluationId:string;subjectType:string;subjectId:string;actionType:string;targetReference?:string|null;enforcementPoint:string;decision:EnforcementDecision;outcome:EnforcementOutcome;attemptedAt:string;completedAt?:string|null;providerReceipt:unknown},kernel:KernelStore):Promise<EnforcementAttempt>{
 const id=randomUUID(),completedAt=input.completedAt??null;
 if(input.outcome==='BLOCKED'&&input.decision!=='BLOCK')throw Error('BLOCKED_REQUIRES_BLOCK_DECISION');
 if(input.outcome==='BLOCKED'&&!completedAt)throw Error('BLOCKED_REQUIRES_COMPLETION');
 if(input.outcome==='UNKNOWN'||input.outcome==='UNAVAILABLE')return seal({id,organizationId:input.organizationId,policyEvaluationId:input.policyEvaluationId,subjectType:input.subjectType,subjectId:input.subjectId,actionType:input.actionType,targetReference:input.targetReference??null,enforcementPoint:input.enforcementPoint,decision:input.decision,outcome:input.outcome,attemptedAt:input.attemptedAt,completedAt,evidenceId:null,evidenceHash:null,preventionState:input.outcome==='UNAVAILABLE'?'UNAVAILABLE':'UNKNOWN'});
 const ev=await kernel.record(input.organizationId,{sourceType:'ENFORCEMENT_POINT',sourceName:input.enforcementPoint,collector:'enforcement-receipt',subjectType:input.subjectType,subjectId:input.subjectId,observationType:'ENFORCEMENT_OUTCOME',content:{policyEvaluationId:input.policyEvaluationId,actionType:input.actionType,targetReference:input.targetReference??null,decision:input.decision,outcome:input.outcome,providerReceipt:input.providerReceipt},observedAt:completedAt??input.attemptedAt,collectedAt:new Date().toISOString(),validationState:'VERIFIED',evidenceType:'ENFORCEMENT_RECEIPT',provenance:{enforcementPoint:input.enforcementPoint}});
 await kernel.bind(input.organizationId,ev.evidenceId,'GOVERNANCE',id,'SUPPORTS');
 return seal({id,organizationId:input.organizationId,policyEvaluationId:input.policyEvaluationId,subjectType:input.subjectType,subjectId:input.subjectId,actionType:input.actionType,targetReference:input.targetReference??null,enforcementPoint:input.enforcementPoint,decision:input.decision,outcome:input.outcome,attemptedAt:input.attemptedAt,completedAt,evidenceId:ev.evidenceId,evidenceHash:ev.digest,preventionState:input.outcome==='BLOCKED'?'PREVENTED':'NOT_PREVENTED'})
}
