import type{Entity,EvidenceState}from'./constellation.js';
export type CelestialKind='STAR'|'PLANET'|'MOON'|'SATELLITE'|'ARTIFACT'|'UNKNOWN';
export type ExplorationState='EXPLORE'|'LIMITED'|'UNKNOWN';
export interface ResourceReading{name:string;unit:string;value:number;evidenceState:EvidenceState;evidenceHash:string;observedAt:string}
export interface UpgradeOffer{id:string;name:string;capability:string;state:'AVAILABLE'|'ACTIVE';evidenceBasis:string}
export interface ExplorableObject{id:string;name:string;kind:CelestialKind;state:ExplorationState;evidenceState:EvidenceState;resources:ResourceReading[];upgrades:UpgradeOffer[]}
const kind=(e:Entity):CelestialKind=>e.entityType==='AI_AGENT'||e.entityType==='MODEL'?'STAR':e.entityType==='TOOL'?'MOON':e.entityType==='OBSERVER'?'SATELLITE':e.entityType==='ARTIFACT'?'ARTIFACT':e.entityType==='SYSTEM'||e.entityType==='DATABASE'||e.entityType==='API'||e.entityType==='WORKLOAD'?'PLANET':'UNKNOWN';
const reading=(x:unknown):ResourceReading|null=>{if(!x||typeof x!=='object')return null;const r=x as Record<string,unknown>;if(typeof r.name!=='string'||typeof r.unit!=='string'||typeof r.value!=='number'||!Number.isFinite(r.value)||typeof r.evidenceHash!=='string'||!/^[a-f0-9]{64}$/.test(r.evidenceHash)||typeof r.observedAt!=='string'||!['OBSERVED','VERIFIED','DECLARED','UNKNOWN','STALE','CONFLICTING','UNAVAILABLE'].includes(String(r.evidenceState)))return null;return{name:r.name,unit:r.unit,value:r.value,evidenceState:r.evidenceState as EvidenceState,evidenceHash:r.evidenceHash,observedAt:r.observedAt}}
export function exploreEntity(e:Entity):ExplorableObject{const m=e.metadata??{},raw=Array.isArray(m.resources)?m.resources:[],resources=raw.map(reading).filter((x):x is ResourceReading=>x!==null);const caps=Array.isArray(m.capabilities)?m.capabilities.filter((x):x is string=>typeof x==='string'):[];const installed=Array.isArray(m.activeCapabilities)?m.activeCapabilities.filter((x):x is string=>typeof x==='string'):[];const upgrades:UpgradeOffer[]=caps.map(c=>({id:c,name:c,capability:c,state:installed.includes(c)?'ACTIVE':'AVAILABLE',evidenceBasis:e.evidenceHash}));const state:ExplorationState=e.evidenceState==='OBSERVED'||e.evidenceState==='VERIFIED'?'EXPLORE':e.evidenceState==='DECLARED'?'LIMITED':'UNKNOWN';return{id:e.id,name:e.name,kind:kind(e),state,evidenceState:e.evidenceState,resources,upgrades}}
