import{createHash,randomUUID}from'node:crypto';
export type EvidenceState='SUPPORTED'|'PARTIAL'|'UNKNOWN'|'CONFLICTING'|'UNSUPPORTED';
export interface Observation{subjectType:string;subjectId:string;state:unknown;evidenceHash:string;source:string;evidenceState:EvidenceState;observedAt:string}
export interface Change{id:string;subjectType:string;subjectId:string;changeType:'CREATED'|'CHANGED'|'UNCHANGED'|'VISIBILITY_LOST';beforeHash:string|null;afterHash:string|null;evidenceHash:string;source:string;evidenceState:EvidenceState;observedAt:string;details:Record<string,unknown>}
export interface Alert{id:string;changeEventId:string|null;severity:'INFO'|'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';status:'OPEN'|'ACKNOWLEDGED'|'RESOLVED';title:string;explanation:string;evidenceState:EvidenceState;createdAt:string}
const valid=(x:string)=>/^[a-f0-9]{64}$/.test(x);export const canonical=(x:unknown):string=>{if(x===null||typeof x!=='object')return JSON.stringify(x);if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';return '{'+Object.entries(x as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+':'+canonical(v)).join(',')+'}'};
export const digest=(x:unknown)=>createHash('sha256').update(canonical(x)).digest('hex');
export function detectChange(previous:Observation|null,current:Observation):Change{if(!valid(current.evidenceHash))throw Error('INVALID_EVIDENCE_HASH');const after=digest(current.state);if(!previous)return{id:randomUUID(),subjectType:current.subjectType,subjectId:current.subjectId,changeType:'CREATED',beforeHash:null,afterHash:after,evidenceHash:current.evidenceHash,source:current.source,evidenceState:current.evidenceState,observedAt:current.observedAt,details:{}};const before=digest(previous.state);return{id:randomUUID(),subjectType:current.subjectType,subjectId:current.subjectId,changeType:before===after?'UNCHANGED':'CHANGED',beforeHash:before,afterHash:after,evidenceHash:current.evidenceHash,source:current.source,evidenceState:current.evidenceState,observedAt:current.observedAt,details:{}}}
export function visibilityLost(previous:Observation,current:{subjectType:string;subjectId:string;source:string;observedAt:string;reason:string}):Change{return{id:randomUUID(),subjectType:current.subjectType,subjectId:current.subjectId,changeType:'VISIBILITY_LOST',beforeHash:digest(previous.state),afterHash:null,evidenceHash:previous.evidenceHash,source:current.source,evidenceState:'UNKNOWN',observedAt:current.observedAt,details:{reason:current.reason,note:'Visibility loss is not evidence of wrongdoing.'}}}
export function alertFor(c:Change):Alert|null{if(c.changeType==='UNCHANGED')return null;const visibility=c.changeType==='VISIBILITY_LOST';return{id:randomUUID(),changeEventId:c.id,severity:visibility?'HIGH':'MEDIUM',status:'OPEN',title:visibility?'Observation visibility lost':`${c.subjectType} changed`,explanation:visibility?'Expected observation became unavailable. Cause and risk remain UNKNOWN.':'Evidence-backed state changed. This is not, by itself, a risk or wrongdoing conclusion.',evidenceState:c.evidenceState,createdAt:new Date().toISOString()}}
export interface OutboxItem{id:string;subscriptionId:string;eventType:string;eventId:string;payload:unknown;payloadHash:string;status:'PENDING'|'DELIVERED'|'FAILED'|'DEAD';attemptCount:number}
export class OutboxMemory{private items=new Map<string,OutboxItem>();enqueue(subscriptionId:string,eventType:string,eventId:string,payload:unknown){const k=[subscriptionId,eventType,eventId].join(':');const old=this.items.get(k);if(old)return structuredClone(old);const v={id:randomUUID(),subscriptionId,eventType,eventId,payload,payloadHash:digest(payload),status:'PENDING' as const,attemptCount:0};this.items.set(k,v);return structuredClone(v)}all(){return [...this.items.values()].map(x=>structuredClone(x))}}