export type GateState='CODE_GATED'|'EXTERNAL_PROOF_REQUIRED';
export interface ReleaseGate{number:number;name:string;state:GateState;proof:string}
export const releaseGates56to99:ReleaseGate[]=[
[56,'races','CODE_GATED','failure-chaos and idempotency gates'],
[57,'queues','CODE_GATED','leased webhook/privacy queues'],
[58,'rate limiting','CODE_GATED','Fastify global rate limit'],
[59,'abuse','CODE_GATED','auth, size and role boundaries'],
[60,'DoS bounds','CODE_GATED','request/upload/response/time bounds'],
[61,'SSRF','CODE_GATED','public HTTPS outbound validation'],
[62,'path traversal','CODE_GATED','resolved-path containment'],
[63,'injection','CODE_GATED','parameterized SQL and strict schemas'],
[64,'dependencies','EXTERNAL_PROOF_REQUIRED','dependency vulnerability state changes over time'],
[65,'supply chain','EXTERNAL_PROOF_REQUIRED','artifact provenance/signing not fully proven'],
[66,'container','EXTERNAL_PROOF_REQUIRED','runtime image/user/capability proof required'],
[67,'network','EXTERNAL_PROOF_REQUIRED','production network policy proof required'],
[68,'TLS','EXTERNAL_PROOF_REQUIRED','production edge/internal TLS proof required'],
[69,'headers','CODE_GATED','helmet enabled globally'],
[70,'CORS','CODE_GATED','no permissive CORS middleware observed'],
[71,'cookies','CODE_GATED','API-key auth; no session-cookie auth path'],
[72,'logging','CODE_GATED','sensitive header/body redaction'],
[73,'audit ledger','CODE_GATED','durable audit/evidence tables'],
[74,'metrics','CODE_GATED','verification metrics present'],
[75,'alerting','CODE_GATED','operational alerts schema/pipeline present'],
[76,'health','CODE_GATED','health/readiness endpoints'],
[77,'observability','CODE_GATED','logs/readiness/metrics foundations'],
[78,'errors','CODE_GATED','fail-closed domain errors'],
[79,'shutdown','CODE_GATED','worker signal shutdown paths'],
[80,'crash recovery','CODE_GATED','leases/retries/idempotency foundations'],
[81,'deployment','EXTERNAL_PROOF_REQUIRED','current production deployment proof required'],
[82,'rollback','EXTERNAL_PROOF_REQUIRED','production rollback drill required'],
[83,'downtime','EXTERNAL_PROOF_REQUIRED','measured deployment outage proof required'],
[84,'env separation','EXTERNAL_PROOF_REQUIRED','live environment separation proof required'],
[85,'CI gate','CODE_GATED','npm check and release-gate tests'],
[86,'browser','EXTERNAL_PROOF_REQUIRED','real browser acceptance required'],
[87,'accessibility','EXTERNAL_PROOF_REQUIRED','accessibility audit required'],
[88,'performance','EXTERNAL_PROOF_REQUIRED','load/performance test required'],
[89,'pagination','CODE_GATED','bounded list limits; integration partial-coverage contract'],
[90,'caching','EXTERNAL_PROOF_REQUIRED','no complete cache correctness proof'],
[91,'billing','CODE_GATED','signed provider event/evidence state foundations'],
[92,'entitlements','CODE_GATED','billing/onboarding state gates present'],
[93,'privacy/export','CODE_GATED','leased export execution and artifact scoping'],
[94,'deletion','CODE_GATED','legal hold and immutable-evidence refusal'],
[95,'compliance mapping','EXTERNAL_PROOF_REQUIRED','framework/certification mapping not independently validated'],
[96,'incident response','CODE_GATED','incident/audit schema foundations'],
[97,'disaster recovery','EXTERNAL_PROOF_REQUIRED','restore drill and RPO/RTO required'],
[98,'external pen test','EXTERNAL_PROOF_REQUIRED','independent test required'],
[99,'real tenant acceptance','EXTERNAL_PROOF_REQUIRED','real tenant end-to-end acceptance required']
].map(([number,name,state,proof])=>({number:number as number,name:name as string,state:state as GateState,proof:proof as string}));
export function gateSummary(){return{codeGated:releaseGates56to99.filter(x=>x.state==='CODE_GATED').length,externalProofRequired:releaseGates56to99.filter(x=>x.state==='EXTERNAL_PROOF_REQUIRED').length,total:releaseGates56to99.length}}
