import Fastify, { type FastifyRequest, type FastifyReply } from 'fastify';
import helmet from '@fastify/helmet';
import multipart from '@fastify/multipart';
import rateLimit from '@fastify/rate-limit';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import fastifyStatic from '@fastify/static';
import { createHash, createHmac, timingSafeEqual } from 'node:crypto';
import { basename, resolve } from 'node:path';
import { z } from 'zod';
import { loadConfig } from './config.js';
import { createStore, type ApiIdentity, type ApiRole } from './db.js';
import { verifyMedia } from './verification/engine.js';
import { deleteStoredMedia, promoteStoredMedia, storeUpload } from './storage.js';
import { scanForMalware } from './security/malware.js';
import { scannerReady } from './security/scanner-readiness.js';
import { canReadTenantRecord } from './tenant.js';
import { createAiStore } from './ai.js';
import { createConstellationStore } from './constellation.js';
import { createAccountabilityStore } from './accountability.js';
import { createKernelStore } from './evidence-store.js';
import { EVIDENCE_DOMAINS, integrateEvidence } from './evidence-integration.js';
import { createInventoryStore } from './inventory-store.js';
import { createGovernanceStore } from './governance-store.js';
import { evaluateAuthority } from './authority.js';
import { createAuthorityStore } from './authority-store.js';
import { executeDiscovery } from './shadow-ai-discovery.js';
import { verifiedEnforcement } from './enforcement.js';
import { persistEnforcementAttempt } from './enforcement-store.js';
import { WebhookDeliveryStore } from './webhook-delivery.js';
import { CustomerProjectionStore } from './customer-projections.js';
import { PrivacyExecutionStore } from './privacy-execution.js';
import { CommerceStore, verifyProviderSignature } from './commerce.js';
import { canGrant, safeWebhookBodySize } from './security-gate.js';
import { StarDnaStore } from './star-dna.js';
import { classifyRoute, RATE_LIMITS } from './operational-hardening.js';
import { TenantQuotaStore } from './tenant-quota.js';
import { startEmbeddedWorkers } from './embedded-workers.js';

const config = loadConfig();
const app = Fastify({ logger: { level: config.LOG_LEVEL, redact: ['req.headers.authorization','req.headers.x-api-key','req.headers.x-billing-signature','req.headers.x-media-signature','req.headers.x-enforcement-signature','req.body.token','req.body.secret','headers.authorization','headers.x-api-key'] }, bodyLimit: config.MAX_UPLOAD_BYTES, requestTimeout: config.REQUEST_TIMEOUT_MS, trustProxy: config.TRUST_PROXY });
const store = createStore(config.DATABASE_URL,{max:config.DB_POOL_MAX,idleTimeoutSeconds:config.DB_IDLE_TIMEOUT_SECONDS,connectTimeoutSeconds:config.DB_CONNECT_TIMEOUT_SECONDS,statementTimeoutMs:config.DB_STATEMENT_TIMEOUT_MS,idleTransactionTimeoutMs:config.DB_IDLE_TRANSACTION_TIMEOUT_MS});
const aiStore = createAiStore(config.DATABASE_URL);
const constellationStore = createConstellationStore(config.DATABASE_URL);
const accountabilityStore = createAccountabilityStore(config.DATABASE_URL);
const kernelStore = createKernelStore(config.DATABASE_URL);
const inventoryStore = createInventoryStore(config.DATABASE_URL);
const governanceStore = createGovernanceStore(config.DATABASE_URL);
const authorityStore = createAuthorityStore(config.DATABASE_URL);
const webhookDeliveryStore = config.DATABASE_URL ? new WebhookDeliveryStore(config.DATABASE_URL) : null;
const customerProjectionStore = config.DATABASE_URL ? new CustomerProjectionStore(config.DATABASE_URL) : null;
const privacyExecutionStore = config.DATABASE_URL ? new PrivacyExecutionStore(config.DATABASE_URL) : null;
const commerceStore = config.DATABASE_URL ? new CommerceStore(config.DATABASE_URL) : null;
const starDnaStore = config.DATABASE_URL ? new StarDnaStore(config.DATABASE_URL) : null;
const tenantQuotaStore = config.DATABASE_URL ? new TenantQuotaStore(config.DATABASE_URL,{statementTimeoutMs:Math.min(config.DB_STATEMENT_TIMEOUT_MS,5000)}) : null;
if(config.RUN_EMBEDDED_WORKERS&&config.DATABASE_URL)startEmbeddedWorkers(config.DATABASE_URL,(x,m)=>app.log.error(x as any,m));
const idPattern = /^[A-Za-z0-9_-]{10,40}$/;
const roles: ApiRole[] = ['viewer','creator','reviewer','moderator','analyst','organization_admin','platform_admin','super_admin'];
const aiStatuses = ['NONE','AI_ASSISTED','AI_EDITED','AI_GENERATED','AI_SYNTHETIC_PERSON','AI_SYNTHETIC_VOICE','AI_DEEPFAKE','UNKNOWN'] as const;
await app.register(helmet, { global: true });
await app.register(rateLimit, { max: config.RATE_LIMIT_MAX, timeWindow: config.RATE_LIMIT_WINDOW_MS });
app.addHook('onRoute',(route:any)=>{const cls=classifyRoute(String(route.method),String(route.url));const limit=RATE_LIMITS[cls];route.config={...(route.config??{}),rateLimit:{max:limit.max,timeWindow:limit.windowMs}}});
await app.register(multipart, { limits: { fileSize: config.MAX_UPLOAD_BYTES, files: 1, fields: 8 } });
await app.register(fastifyStatic, { root: resolve('public'), prefix: '/' });
await app.register(swagger, { openapi: { info: { title: 'Media Passport API', version: '1.0.0' }, servers: [{ url: '/' }], tags: [{ name: 'media' }, { name: 'passport' }, { name: 'trust' }, { name: 'cases' }, { name: 'admin' }] } });
await app.register(swaggerUi, { routePrefix: '/docs' });
const publicPath = (url: string) => { const path = new URL(url, 'http://localhost').pathname; return path === '/health' || path === '/ready' || path === '/ready/ai' || path === '/' || path === '/v1/integrations/action-confirmations' || path === '/v1/billing/provider-events' || path.startsWith('/public/') || path.startsWith('/passport/') || path.startsWith('/app.') || path.startsWith('/styles.') || path.startsWith('/passport.') || path === '/ai.html' || path === '/ai.js' || path === '/docs' || path.startsWith('/docs/'); };
app.decorateRequest('mediaAuth', null);
app.addHook('onRequest', async (req, reply) => {
  if (publicPath(req.url) || !config.REQUIRE_API_KEY) return;
  const supplied = req.headers['x-api-key'];
  const rejectAuth=async()=>{if(tenantQuotaStore){const key='auth:'+createHash('sha256').update(req.ip).digest('hex');const lim=RATE_LIMITS.AUTH_FAILURE;const q=await tenantQuotaStore.consume(key,'AUTH_FAILURE',lim.max,lim.windowMs);if(!q.allowed)return reply.code(429).send({error:'AUTH_RATE_LIMITED',resetAt:q.resetAt})}return reply.code(401).send({error:'UNAUTHORIZED'})};
  if (typeof supplied !== 'string') return rejectAuth();
  const expected = config.API_KEY;
  if (expected) { const suppliedBuffer = Buffer.from(supplied); const expectedBuffer = Buffer.from(expected); if (suppliedBuffer.length === expectedBuffer.length && timingSafeEqual(suppliedBuffer, expectedBuffer)) { req.mediaAuth = { keyId: 'bootstrap', organizationId: null, role: config.BOOTSTRAP_API_ROLE }; return; } }
  const identity = await store.authenticateApiKey(supplied);
  if (!identity) { req.log.warn({ ip:req.ip, route:req.routeOptions?.url ?? new URL(req.url,'http://localhost').pathname }, 'authentication rejected'); return rejectAuth(); }
  req.mediaAuth = identity;
});
function auth(req: { mediaAuth: ApiIdentity | null }): ApiIdentity { if (!req.mediaAuth) throw new Error('UNAUTHORIZED'); return req.mediaAuth; }
const tenantReadRoles:ApiRole[]=['viewer','creator','reviewer','moderator','analyst','organization_admin','platform_admin','super_admin'];
const sensitiveReadRoles:ApiRole[]=['reviewer','moderator','analyst','organization_admin','platform_admin','super_admin'];
function requireRole(req:FastifyRequest & {mediaAuth:ApiIdentity|null},reply:any,allowed:ApiRole[]):boolean{const identity=auth(req);if(!allowed.includes(identity.role)){req.log.warn({keyId:identity.keyId,organizationId:identity.organizationId,role:identity.role},'authorization rejected');void reply.code(403).send({error:'FORBIDDEN'});return false}return true}
function requireTenantRead(req:any,reply:any,sensitive=false):boolean{return requireRole(req,reply,sensitive?sensitiveReadRoles:tenantReadRoles)}
app.addHook('preHandler',async(req,reply)=>{if(publicPath(req.url)||!req.mediaAuth?.organizationId||!tenantQuotaStore)return;const path=new URL(req.url,'http://localhost').pathname;const cls=classifyRoute(req.method,path);const lim=RATE_LIMITS[cls];const q=await tenantQuotaStore.consume(req.mediaAuth.organizationId,cls,lim.max,lim.windowMs);reply.header('x-ratelimit-remaining',String(q.remaining));if(q.resetAt)reply.header('x-ratelimit-reset',q.resetAt);if(!q.allowed)return reply.code(429).send({error:'TENANT_RATE_LIMITED',rateClass:cls,resetAt:q.resetAt})});
app.get('/health', async () => ({ status: 'ok', service: 'constellation', version: '1.0.0', release: config.RELEASE_COMMIT }));
app.get('/ready', async (_req, reply) => {
  const databaseOk = await store.ready(); const databaseRoleSafe = config.NODE_ENV==='production' ? await store.tenantIsolationRoleSafe() : true; const evidenceOk=await kernelStore.ready(); const inventoryOk=await inventoryStore.ready(); const governanceOk=await governanceStore.ready(); let scannerOk = false;
  scannerOk = await scannerReady(config.MALWARE_SCAN_URL,config.MALWARE_SCAN_TOKEN,config.MALWARE_SCAN_TIMEOUT_MS);
  if (!databaseOk || !databaseRoleSafe || !evidenceOk || !inventoryOk || !governanceOk || (config.NODE_ENV === 'production' && !scannerOk)) return reply.code(503).send({ status: 'not_ready', database: { ok: databaseOk, tenantRoleSafe: databaseRoleSafe }, evidence:{ok:evidenceOk}, inventory:{ok:inventoryOk}, governance:{ok:governanceOk}, scanner: { ok: scannerOk } });
  return { status: 'ready', database: { ok: true, tenantRoleSafe: true }, evidence:{ok:true}, inventory:{ok:true}, governance:{ok:true}, scanner: { ok: scannerOk }, trustEngine: { ok: true } };
});
app.get('/ready/ai', async (_req, reply) => {
 const databaseOk = await aiStore.ready();
 return reply.code(databaseOk ? 200 : 503).send({ status: databaseOk ? 'ready' : 'not_ready', scope: 'ai_registry_and_event_api', database: { ok: databaseOk }, mediaScanning: { status: 'NOT_ASSESSED', note: 'Use /ready for the media upload and malware scanner pipeline.' } });
});
app.post('/v1/billing/provider-events',async(req,reply)=>{if(!config.BILLING_WEBHOOK_SECRET||!commerceStore)return reply.code(503).send({error:'BILLING_PROVIDER_NOT_CONFIGURED'});const raw=safeWebhookBodySize(JSON.stringify(req.body??{}),config.WEBHOOK_INGRESS_MAX_BYTES);const sig=typeof req.headers['x-billing-signature']==='string'?req.headers['x-billing-signature']:undefined;if(!verifyProviderSignature(config.BILLING_WEBHOOK_SECRET,raw,sig))return reply.code(401).send({error:'INVALID_BILLING_SIGNATURE'});const b=z.object({id:z.string().regex(/^[A-Za-z0-9_.:-]{1,200}$/),type:z.string().regex(/^[A-Za-z0-9_.:-]{1,100}$/),organizationId:z.string().min(1).max(100),customerId:z.string().min(1).max(200).optional(),accountStatus:z.enum(['UNKNOWN','PENDING','ACTIVE','PAST_DUE','CANCELED','FAILED']),subscriptionStatus:z.enum(['UNKNOWN','PENDING','ACTIVE','PAST_DUE','CANCELED','FAILED']),occurredAt:z.iso.datetime({offset:true})}).strict().parse(req.body);try{return reply.code(202).send(await commerceStore.providerEvent(config.BILLING_WEBHOOK_PROVIDER,b,raw,config.BILLING_WEBHOOK_KEY_ID))}catch(e){if(e instanceof Error&&e.message==='BILLING_EVENT_REPLAY_MISMATCH')return reply.code(409).send({error:e.message});throw e}});
app.get('/v1/billing/status',async(req,reply)=>{if(!requireTenantRead(req,reply,false))return;const org=tenant(req,reply);if(!org)return;if(!commerceStore)return reply.code(503).send({error:'BILLING_STORE_UNAVAILABLE'});return commerceStore.billing(org)});
app.get('/v1/onboarding/status',async(req,reply)=>{if(!requireTenantRead(req,reply,false))return;const org=tenant(req,reply);if(!org)return;if(!commerceStore)return reply.code(503).send({error:'ONBOARDING_STORE_UNAVAILABLE'});return commerceStore.onboard(org)});
app.post('/v1/onboarding/steps/:name',async(req,reply)=>{if(!requireRole(req,reply,['organization_admin','platform_admin','super_admin']))return;const org=tenant(req,reply);if(!org)return;if(!commerceStore)return reply.code(503).send({error:'ONBOARDING_STORE_UNAVAILABLE'});const name=z.string().regex(/^[A-Za-z0-9_.:-]{1,100}$/).parse((req.params as{name:string}).name);const b=z.object({state:z.enum(['PENDING','COMPLETE','BLOCKED']),evidenceHash:z.string().regex(/^[a-f0-9]{64}$/).optional()}).strict().parse(req.body);try{return await commerceStore.step(org,name,b.state,auth(req).keyId,b.evidenceHash)}catch(e){if(e instanceof Error&&e.message==='COMPLETED_STEP_REQUIRES_BACKEND_EVIDENCE')return reply.code(409).send({error:e.message});throw e}});
app.post('/v1/privacy/deletions',async(req,reply)=>{if(!requireRole(req,reply,['organization_admin','platform_admin','super_admin']))return;const org=tenant(req,reply);if(!org)return;if(!privacyExecutionStore)return reply.code(503).send({error:'PRIVACY_STORE_UNAVAILABLE'});const b=z.object({subjectType:z.string().min(1).max(80),subjectId:z.string().min(1).max(200),reason:z.string().min(1).max(1000)}).strict().parse(req.body);return reply.code(202).send(await privacyExecutionStore.requestDeletion(org,b.subjectType,b.subjectId,auth(req).keyId,b.reason))});
app.post('/v1/privacy/deletions/:id/legal-hold',async(req,reply)=>{if(!requireRole(req,reply,['organization_admin','platform_admin','super_admin']))return;const org=tenant(req,reply);if(!org)return;if(!privacyExecutionStore)return reply.code(503).send({error:'PRIVACY_STORE_UNAVAILABLE'});const id=z.uuid().parse((req.params as{id:string}).id);const b=z.object({reason:z.string().min(1).max(1000)}).parse(req.body);const ok=await privacyExecutionStore.legalHold(org,id,auth(req).keyId,b.reason);return ok?reply.code(200).send({status:'LEGAL_HOLD'}):reply.code(404).send({error:'REQUEST_NOT_FOUND_OR_NOT_HOLDABLE'})});
app.get('/v1/privacy/deletions/:id',async(req,reply)=>{if(!requireTenantRead(req,reply,true))return;const org=tenant(req,reply);if(!org)return;if(!privacyExecutionStore)return reply.code(503).send({error:'PRIVACY_STORE_UNAVAILABLE'});const id=z.uuid().parse((req.params as{id:string}).id);return await privacyExecutionStore.job(org,'DELETION',id)??reply.code(404).send({error:'NOT_FOUND'})});
app.post('/v1/privacy/exports',async(req,reply)=>{if(!requireRole(req,reply,['analyst','organization_admin','platform_admin','super_admin']))return;const org=tenant(req,reply);if(!org)return;if(!privacyExecutionStore)return reply.code(503).send({error:'PRIVACY_STORE_UNAVAILABLE'});const b=z.object({exportType:z.string().regex(/^[A-Za-z0-9_.:-]{1,100}$/),asOf:z.iso.datetime({offset:true}).default(new Date().toISOString())}).strict().parse(req.body);return reply.code(202).send(await privacyExecutionStore.requestExport(org,b.exportType,b.asOf,auth(req).keyId))});
app.get('/v1/privacy/exports/:id',async(req,reply)=>{if(!requireTenantRead(req,reply,true))return;const org=tenant(req,reply);if(!org)return;if(!privacyExecutionStore)return reply.code(503).send({error:'PRIVACY_STORE_UNAVAILABLE'});const id=z.uuid().parse((req.params as{id:string}).id);return await privacyExecutionStore.job(org,'EXPORT',id)??reply.code(404).send({error:'NOT_FOUND'})});
app.get('/v1/privacy/exports/:id/artifact',async(req,reply)=>{if(!requireTenantRead(req,reply,true))return;const org=tenant(req,reply);if(!org)return;if(!privacyExecutionStore)return reply.code(503).send({error:'PRIVACY_STORE_UNAVAILABLE'});const id=z.uuid().parse((req.params as{id:string}).id);return await privacyExecutionStore.artifact(org,id)??reply.code(404).send({error:'NOT_FOUND_OR_INCOMPLETE'})});
app.get('/v1/customer/dashboard',async(req,reply)=>{if(!requireTenantRead(req,reply,false))return;const org=tenant(req,reply);if(!org)return;if(!customerProjectionStore)return reply.code(503).send({error:'REPORTING_STORE_UNAVAILABLE'});const q=z.object({asOf:z.iso.datetime({offset:true}).default(new Date().toISOString()),limit:z.coerce.number().int().min(1).max(500).default(100)}).parse(req.query);return customerProjectionStore.dashboard(org,q.asOf,q.limit)});
app.get('/v1/customer/passports/:subjectType/:subjectId',async(req,reply)=>{if(!requireTenantRead(req,reply,false))return;const org=tenant(req,reply);if(!org)return;if(!customerProjectionStore)return reply.code(503).send({error:'REPORTING_STORE_UNAVAILABLE'});const p=z.object({subjectType:z.string().min(1).max(80),subjectId:z.string().min(1).max(200)}).parse(req.params);const q=z.object({asOf:z.iso.datetime({offset:true}).default(new Date().toISOString())}).parse(req.query);return customerProjectionStore.passport(org,p.subjectType,p.subjectId,q.asOf)});
app.get('/v1/customer/timeline/:subjectType/:subjectId',async(req,reply)=>{if(!requireTenantRead(req,reply,false))return;const org=tenant(req,reply);if(!org)return;if(!customerProjectionStore)return reply.code(503).send({error:'REPORTING_STORE_UNAVAILABLE'});const p=z.object({subjectType:z.string().min(1).max(80),subjectId:z.string().min(1).max(200)}).parse(req.params);const q=z.object({asOf:z.iso.datetime({offset:true}).default(new Date().toISOString()),limit:z.coerce.number().int().min(1).max(500).default(250)}).parse(req.query);return customerProjectionStore.timeline(org,p.subjectType,p.subjectId,q.asOf,q.limit)});
app.get('/v1/customer/constellation',async(req,reply)=>{if(!requireTenantRead(req,reply,false))return;const org=tenant(req,reply);if(!org)return;const q=z.object({asOf:z.iso.datetime({offset:true}).default(new Date().toISOString()),limit:z.coerce.number().int().min(1).max(500).default(250)}).parse(req.query);return constellationStore.snapshot(org,q.asOf,q.limit)});
app.post('/v1/customer/reports',async(req,reply)=>{if(!requireRole(req,reply,['analyst','organization_admin','platform_admin','super_admin']))return;const org=tenant(req,reply);if(!org)return;if(!customerProjectionStore)return reply.code(503).send({error:'REPORTING_STORE_UNAVAILABLE'});const b=z.object({reportType:z.string().regex(/^[A-Za-z0-9_.:-]{1,100}$/),asOf:z.iso.datetime({offset:true}).default(new Date().toISOString())}).parse(req.body);return reply.code(201).send(await customerProjectionStore.createReport(org,b.reportType,b.asOf))});
app.get('/v1/customer/reports',async(req,reply)=>{if(!requireTenantRead(req,reply,false))return;const org=tenant(req,reply);if(!org)return;if(!customerProjectionStore)return reply.code(503).send({error:'REPORTING_STORE_UNAVAILABLE'});const q=z.object({limit:z.coerce.number().int().min(1).max(100).default(50)}).parse(req.query);return{reports:await customerProjectionStore.reports(org,q.limit)}});
app.get('/v1/webhooks/operations',async(req,reply)=>{if(!requireRole(req,reply,['organization_admin','platform_admin','super_admin']))return;const org=tenant(req,reply);if(!org)return;if(!webhookDeliveryStore)return reply.code(503).send({error:'WEBHOOK_STORE_UNAVAILABLE'});return{organizationId:org,queue:await webhookDeliveryStore.health(org)}});
app.get('/v1/webhooks/deliveries/:id/history',async(req,reply)=>{if(!requireRole(req,reply,['organization_admin','platform_admin','super_admin']))return;const org=tenant(req,reply);if(!org)return;if(!webhookDeliveryStore)return reply.code(503).send({error:'WEBHOOK_STORE_UNAVAILABLE'});const id=z.uuid().parse((req.params as{id:string}).id);return{outboxId:id,attempts:await webhookDeliveryStore.history(org,id)}});
app.post('/v1/webhooks/deliveries/:id/requeue',async(req,reply)=>{if(!requireRole(req,reply,['organization_admin','platform_admin','super_admin']))return;const org=tenant(req,reply);if(!org)return;if(!webhookDeliveryStore)return reply.code(503).send({error:'WEBHOOK_STORE_UNAVAILABLE'});const id=z.uuid().parse((req.params as{id:string}).id);const ok=await webhookDeliveryStore.requeue(org,id,auth(req).keyId);return ok?reply.code(202).send({status:'REQUEUED',outboxId:id}):reply.code(404).send({error:'DEAD_LETTER_NOT_FOUND'})});
app.post('/v1/organizations', async (req, reply) => { if (!requireRole(req, reply, ['super_admin','platform_admin'])) return; const body = z.object({ name: z.string().trim().min(2).max(120) }).parse(req.body); const created = await store.createOrganization(body.name); return reply.code(201).send(created); });
app.post('/v1/api-keys', async (req, reply) => { if (!requireRole(req, reply, ['super_admin','platform_admin','organization_admin'])) return; const identity=auth(req); const body=z.object({organizationId:z.string().min(1).max(100),name:z.string().trim().min(1).max(100),role:z.enum(roles as [ApiRole,...ApiRole[]]),expiresAt:z.iso.datetime({offset:true}).nullable().optional()}).strict().parse(req.body); if(body.expiresAt&&Date.parse(body.expiresAt)<=Date.now())return reply.code(400).send({error:'EXPIRY_MUST_BE_FUTURE'}); if(identity.organizationId&&identity.organizationId!==body.organizationId&&!['super_admin','platform_admin'].includes(identity.role))return reply.code(403).send({error:'TENANT_MISMATCH'}); if(!canGrant(identity.role,body.role))return reply.code(403).send({error:'ROLE_ESCALATION_DENIED'}); const created=await store.createApiKey(body.organizationId,body.name,body.role,body.expiresAt??null); return reply.code(201).send({...created,warning:'The secret is returned once. Store it securely.'}); });
app.get('/v1/api-keys',async(req,reply)=>{if(!requireRole(req,reply,['organization_admin','platform_admin','super_admin']))return;const identity=auth(req);const q=z.object({organizationId:z.string().min(1).max(100).optional()}).parse(req.query);const organizationId=identity.organizationId??q.organizationId;if(!organizationId)return reply.code(400).send({error:'ORGANIZATION_REQUIRED'});if(identity.organizationId&&q.organizationId&&q.organizationId!==identity.organizationId)return reply.code(403).send({error:'TENANT_MISMATCH'});return{keys:await store.listApiKeys(organizationId)}});
app.post('/v1/api-keys/:id/revoke',async(req,reply)=>{if(!requireRole(req,reply,['organization_admin','platform_admin','super_admin']))return;const identity=auth(req);if(identity.keyId===(req.params as{id:string}).id)return reply.code(409).send({error:'SELF_REVOCATION_REQUIRES_ROTATION'});const q=z.object({organizationId:z.string().min(1).max(100).optional()}).parse(req.query);const organizationId=identity.organizationId??q.organizationId;if(!organizationId)return reply.code(400).send({error:'ORGANIZATION_REQUIRED'});if(identity.organizationId&&q.organizationId&&q.organizationId!==identity.organizationId)return reply.code(403).send({error:'TENANT_MISMATCH'});const ok=await store.revokeApiKey(organizationId,(req.params as{id:string}).id);return ok?reply.code(200).send({status:'REVOKED'}):reply.code(404).send({error:'KEY_NOT_FOUND_OR_ALREADY_REVOKED'})});
app.post('/v1/api-keys/:id/rotate',async(req,reply)=>{if(!requireRole(req,reply,['organization_admin','platform_admin','super_admin']))return;const identity=auth(req);const body=z.object({organizationId:z.string().min(1).max(100).optional(),name:z.string().trim().min(1).max(100),role:z.enum(roles as [ApiRole,...ApiRole[]]),expiresAt:z.iso.datetime({offset:true}).nullable().optional()}).strict().parse(req.body);if(body.expiresAt&&Date.parse(body.expiresAt)<=Date.now())return reply.code(400).send({error:'EXPIRY_MUST_BE_FUTURE'});const organizationId=identity.organizationId??body.organizationId;if(!organizationId)return reply.code(400).send({error:'ORGANIZATION_REQUIRED'});if(identity.organizationId&&body.organizationId&&body.organizationId!==identity.organizationId)return reply.code(403).send({error:'TENANT_MISMATCH'});if(!canGrant(identity.role,body.role))return reply.code(403).send({error:'ROLE_ESCALATION_DENIED'});const created=await store.rotateApiKey(organizationId,(req.params as{id:string}).id,body.name,body.role,body.expiresAt??null);return created?reply.code(201).send({...created,warning:'The replacement secret is returned once. The old key is revoked.'}):reply.code(404).send({error:'KEY_NOT_FOUND_OR_ALREADY_REVOKED'})});
const aiWriterRoles: ApiRole[] = ['analyst','organization_admin','platform_admin','super_admin'];
function tenant(req: FastifyRequest, reply: FastifyReply): string | null { const id = auth(req).organizationId; if (!id) { void reply.code(403).send({ error: 'TENANT_KEY_REQUIRED' }); return null; } return id; }
const evidenceState=z.enum(['OBSERVED','VERIFIED','DECLARED','UNKNOWN','STALE','CONFLICTING','UNAVAILABLE']);const hash=z.string().regex(/^[a-f0-9]{64}$/);const metadata=z.record(z.string(),z.unknown()).default({});
app.post('/v1/constellation/entities',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({identityKey:z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,199}$/),entityType:z.enum(['AI_AGENT','MODEL','HUMAN','TOOL','API','DATABASE','OBSERVER','POLICY','SYSTEM','WORKLOAD','CREDENTIAL','ARTIFACT','UNKNOWN']),name:z.string().trim().min(1).max(160),evidenceState,evidenceHash:hash,source:z.string().min(1).max(200),firstObservedAt:z.iso.datetime({offset:true}),lastObservedAt:z.iso.datetime({offset:true}),metadata}).parse(req.body);return reply.code(201).send(await constellationStore.addEntity(org,b))});
app.post('/v1/constellation/relationships',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({fromEntityId:z.uuid(),toEntityId:z.uuid(),relationshipType:z.enum(['ORBIT','CLUSTER','WORMHOLE','DEPENDENCY','INTERACTION','PROVENANCE','OBSERVATION','POLICY_APPLIES','TRANSIENT']),evidenceState,evidenceHash:hash,source:z.string().min(1).max(200),observedAt:z.iso.datetime({offset:true}),endedAt:z.iso.datetime({offset:true}).nullable().default(null),metadata}).parse(req.body);const v=await constellationStore.addRelationship(org,b);return v?reply.code(201).send(v):reply.code(404).send({error:'RELATED_ENTITY_NOT_FOUND'})});
app.post('/v1/constellation/events',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({eventType:z.enum(['SUPERNOVA','BLACK_HOLE','NEBULA','CHANGE','BOUNDARY','VISIBILITY_LOSS']),entityId:z.uuid().nullable().default(null),relationshipId:z.uuid().nullable().default(null),evidenceState,evidenceHash:hash,summary:z.string().min(1).max(1000),source:z.string().min(1).max(200),occurredAt:z.iso.datetime({offset:true}),metadata}).refine(x=>x.entityId||x.relationshipId,{message:'entityId or relationshipId is required'}).parse(req.body);const v=await constellationStore.addEvent(org,b);return v?reply.code(201).send(v):reply.code(404).send({error:'RELATED_OBJECT_NOT_FOUND'})});
app.post('/v1/constellation/star-dna',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;if(!starDnaStore)return reply.code(503).send({error:'STAR_DNA_STORE_UNAVAILABLE'});const b=z.object({parentEntityId:z.uuid(),childEntityId:z.uuid(),edgeType:z.enum(['CREATED','DELEGATED','INVOKED','USED_TOOL','ACCESSED_RESOURCE','DERIVED_FROM','OTHER']),evidenceHash:hash,source:z.string().min(1).max(200),occurredAt:z.iso.datetime({offset:true}),observedAt:z.iso.datetime({offset:true})}).strict().parse(req.body);const v=await starDnaStore.add(org,b);return v?reply.code(201).send(v):reply.code(404).send({error:'RELATED_ENTITY_NOT_FOUND'})});
app.get('/v1/constellation/star-dna/:entityId',async(req,reply)=>{if(!requireTenantRead(req,reply,true))return;const org=tenant(req,reply);if(!org)return;if(!starDnaStore)return reply.code(503).send({error:'STAR_DNA_STORE_UNAVAILABLE'});const entityId=z.uuid().parse((req.params as{entityId:string}).entityId);const q=z.object({asOf:z.iso.datetime({offset:true}).default(new Date().toISOString()),limit:z.coerce.number().int().min(1).max(500).default(250)}).parse(req.query);return{organizationId:org,entityId,asOf:q.asOf,edges:await starDnaStore.lineage(org,entityId,q.asOf,q.limit),note:'Only persisted tenant-scoped provenance edges are returned. Missing ancestry is UNKNOWN.'}});
app.get('/v1/constellation',async(req,reply)=>{if(!requireTenantRead(req,reply,false))return;const org=tenant(req,reply);if(!org)return;const q=z.object({asOf:z.iso.datetime({offset:true}).default(new Date().toISOString()),limit:z.coerce.number().int().min(1).max(500).default(250)}).parse(req.query);return constellationStore.snapshot(org,q.asOf,q.limit)});
app.post('/v1/evidence/observations',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({sourceType:z.string().trim().min(1).max(80),sourceName:z.string().trim().min(1).max(160),collector:z.string().trim().min(1).max(160),subjectType:z.string().trim().min(1).max(80),subjectId:z.string().trim().min(1).max(200),observationType:z.string().trim().min(1).max(100),content:z.unknown(),observedAt:z.iso.datetime({offset:true}),collectedAt:z.iso.datetime({offset:true}),validationState:z.enum(['OBSERVED','DECLARED','UNKNOWN','STALE','CONFLICTING','UNAVAILABLE']),evidenceType:z.string().trim().min(1).max(80),contentReference:z.string().max(1000).nullable().optional(),provenance:z.record(z.string().max(100),z.unknown()).default({})}).strict().superRefine((x,ctx)=>{if(Date.parse(x.collectedAt)<Date.parse(x.observedAt))ctx.addIssue({code:'custom',message:'EVIDENCE_COLLECTED_BEFORE_OBSERVED'});let contentBytes=Infinity,provenanceBytes=Infinity;try{contentBytes=Buffer.byteLength(JSON.stringify(x.content));provenanceBytes=Buffer.byteLength(JSON.stringify(x.provenance))}catch{}if(contentBytes>262144)ctx.addIssue({code:'custom',message:'EVIDENCE_CONTENT_TOO_LARGE'});if(provenanceBytes>65536)ctx.addIssue({code:'custom',message:'EVIDENCE_PROVENANCE_TOO_LARGE'})}).parse(req.body);return reply.code(201).send(await kernelStore.record(org,b))});
app.post('/v1/evidence/claims',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({subjectType:z.string().min(1).max(80),subjectId:z.string().min(1).max(200),claimType:z.string().min(1).max(100),claimText:z.string().min(1).max(2000),findingType:z.string().min(1).max(100),state:z.enum(['SUPPORTED','PARTIAL','UNKNOWN','CONFLICTING','UNSUPPORTED']),summary:z.string().min(1).max(2000),evidenceIds:z.array(z.uuid()).min(1).max(100)}).parse(req.body);const v=await kernelStore.claim(org,b);return v?reply.code(201).send(v):reply.code(400).send({error:'EVIDENCE_NOT_FOUND_OR_TENANT_MISMATCH'})});
app.get('/v1/evidence/claims/:id/lineage',async(req,reply)=>{if(!requireTenantRead(req,reply,true))return;const org=tenant(req,reply);if(!org)return;const id=z.uuid().parse((req.params as{id:string}).id);const v=await kernelStore.lineage(org,id);return v??reply.code(404).send({error:'NOT_FOUND'})});
app.post('/v1/evidence/integrate',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({domain:z.enum(EVIDENCE_DOMAINS),recordId:z.string().min(1).max(200),subjectType:z.string().min(1).max(80),subjectId:z.string().min(1).max(200),claimType:z.string().min(1).max(100),claimText:z.string().min(1).max(2000),findingType:z.string().min(1).max(100),state:z.enum(['SUPPORTED','PARTIAL','UNKNOWN','CONFLICTING','UNSUPPORTED']),summary:z.string().min(1).max(2000),evidenceIds:z.array(z.uuid()).max(100)}).strict().parse(req.body);return reply.code(201).send(await integrateEvidence(kernelStore,org,b))});
app.post('/v1/evidence/bindings',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({evidenceId:z.uuid(),domain:z.enum(EVIDENCE_DOMAINS),domainRecordId:z.string().min(1).max(200),bindingType:z.enum(['SUPPORTS','OBSERVES','DERIVED_FROM','EVALUATES'])}).parse(req.body);return await kernelStore.bind(org,b.evidenceId,b.domain,b.domainRecordId,b.bindingType)?reply.code(201).send({bound:true}):reply.code(404).send({error:'EVIDENCE_NOT_FOUND'})});
app.get('/v1/evidence/bindings/:domain/:recordId',async(req,reply)=>{if(!requireTenantRead(req,reply,true))return;const org=tenant(req,reply);if(!org)return;const p=z.object({domain:z.enum(EVIDENCE_DOMAINS),recordId:z.string().min(1).max(200)}).parse(req.params);return{bindings:await kernelStore.bindings(org,p.domain,p.recordId)}});
app.post('/v1/ai/:id/accountability',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({eventId:z.uuid().nullable().default(null),metricType:z.enum(['AI_EXECUTION_TIME','MODEL_COST','TOKEN_COST','TOOL_COST','API_COST','INFRASTRUCTURE_COST','RETRY','FAILED_ACTION','REPEATED_INSTRUCTION','CORRECTION','BACKTRACK','UNDO','REWORK','HUMAN_INTERVENTION','HUMAN_WAIT_TIME','HUMAN_CORRECTION_TIME','RECOVERY_DURATION','TIME_SAVED','COST_AVOIDED','SUCCESSFUL_ACTION','FIRST_ATTEMPT_COMPLETION','AUTONOMOUS_COMPLETION']),value:z.number().nonnegative(),unit:z.enum(['MILLISECONDS','COUNT','TOKENS','USD','CAD','SECONDS','MINUTES']),valueState:z.enum(['OBSERVED','CALCULATED','CONFIGURED','ESTIMATED','UNKNOWN']),attribution:z.enum(['AI','HUMAN','TOOL','INTEGRATION','EXTERNAL','MIXED','UNKNOWN']),evidenceHash:hash,source:z.string().min(1).max(200),occurredAt:z.iso.datetime({offset:true}),calculation:z.record(z.string(),z.unknown()).default({}),evidenceIds:z.array(z.uuid()).max(100)}).parse(req.body);const {evidenceIds,...entry}=b;const e=await accountabilityStore.append(org,{aiId:(req.params as{id:string}).id,...entry});if(!e)return reply.code(404).send({error:'AI_NOT_FOUND'});await integrateEvidence(kernelStore,org,{domain:'AI_ACCOUNTABILITY',recordId:e.id,subjectType:'AI',subjectId:e.aiId,claimType:e.metricType,claimText:`${e.metricType} ${e.value} ${e.unit}`,findingType:'ACCOUNTABILITY_METRIC',state:e.valueState==='OBSERVED'?'SUPPORTED':e.valueState==='UNKNOWN'?'UNKNOWN':'PARTIAL',summary:`${e.valueState} accountability metric from ${e.source}`,evidenceIds});return reply.code(201).send(e)});
app.get('/v1/ai/:id/accountability',async(req,reply)=>{if(!requireTenantRead(req,reply,true))return;const org=tenant(req,reply);if(!org)return;if(!await aiStore.get(org,(req.params as{id:string}).id))return reply.code(404).send({error:'NOT_FOUND'});return accountabilityStore.statement(org,(req.params as{id:string}).id)});
app.post('/v1/ai-inventory/collect',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({provider:z.enum(['OPENAI','ANTHROPIC','AI_GATEWAY','SAAS_INVENTORY']),baseUrl:z.url(),token:z.string().min(8).max(4096),path:z.string().startsWith('/').max(500),timeoutMs:z.number().int().min(500).max(30000).optional(),maxBytes:z.number().int().min(1024).max(5000000).optional()}).strict().parse(req.body);const collectorConfig={provider:b.provider,baseUrl:b.baseUrl,token:b.token,path:b.path,...(b.timeoutMs===undefined?{}:{timeoutMs:b.timeoutMs}),...(b.maxBytes===undefined?{}:{maxBytes:b.maxBytes})};const result=await executeDiscovery(org,collectorConfig,inventoryStore,kernelStore,config.DATABASE_URL);return reply.code(201).send(result)});
app.get('/v1/ai-inventory',async(req,reply)=>{if(!requireTenantRead(req,reply,false))return;const org=tenant(req,reply);if(!org)return;return inventoryStore.inventory(org)});
app.post('/v1/authority/check',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({actorEntityId:z.uuid(),missionId:z.uuid(),actionType:z.string().trim().min(1).max(120),targetResourceId:z.uuid().nullable().optional()}).strict().parse(req.body);const input={actorEntityId:b.actorEntityId,missionId:b.missionId,actionType:b.actionType,...(b.targetResourceId!==undefined?{targetResourceId:b.targetResourceId}:{})};const result=await authorityStore.check(org,input);return reply.code(200).send({...result,organizationId:org,enforcementOutcome:'NOT_ATTEMPTED',authoritySource:'PERSISTED_TENANT_EVIDENCE'})});
app.post('/v1/authority/evaluate',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const h=z.string().regex(/^[a-f0-9]{64}$/);const b=z.object({actorEntityId:z.uuid(),actionType:z.string().trim().min(1).max(120),targetResourceId:z.uuid().nullable().optional(),license:z.object({id:z.uuid(),licenseClass:z.number().int().min(0).max(7),validFrom:z.iso.datetime({offset:true}),validUntil:z.iso.datetime({offset:true}).nullable().optional(),evidenceHash:h}).nullable().optional(),mission:z.object({id:z.uuid(),maxLicenseClass:z.number().int().min(0).max(7),startsAt:z.iso.datetime({offset:true}),expiresAt:z.iso.datetime({offset:true}),endedAt:z.iso.datetime({offset:true}).nullable().optional(),evidenceHash:h}).nullable().optional(),approval:z.object({required:z.boolean(),decision:z.enum(['APPROVED','DENIED','UNKNOWN']).optional(),validUntil:z.iso.datetime({offset:true}).nullable().optional(),evidenceHash:h.nullable().optional()}).nullable().optional(),authorityStatus:z.enum(['ACTIVE','EXPIRED','REVOKED','SUSPENDED','UNKNOWN']).optional(),freshness:z.enum(['CURRENT','STALE','UNKNOWN']).optional(),budget:z.enum(['WITHIN_BUDGET','OVER_BUDGET','UNKNOWN']).nullable().optional(),law:z.enum(['SUPPORTED','PARTIAL','UNSUPPORTED','UNKNOWN','CONFLICTING','NOT_APPLICABLE']).nullable().optional()}).parse(req.body);const clean=JSON.parse(JSON.stringify(b));const result=evaluateAuthority(clean);return reply.code(200).send({...result,organizationId:org,enforcementOutcome:'NOT_ATTEMPTED',note:'This endpoint evaluates supplied authority evidence only. It does not execute or claim to block the action.'})});
app.post('/v1/governance/policies',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({version:z.number().int().positive().default(1),name:z.string().min(1).max(160),kind:z.enum(['BOUNDARY','POLICY']),status:z.enum(['DRAFT','ACTIVE','RETIRED']),conditions:z.array(z.object({field:z.string().min(1).max(100),op:z.enum(['EQ','NEQ','IN','GT','GTE','LT','LTE']),value:z.unknown()})).max(100)}).parse(req.body);return reply.code(201).send(await governanceStore.addPolicy(org,b))});
app.post('/v1/governance/enforcement/receipts',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const b=z.object({policyEvaluationId:z.uuid(),subjectType:z.string().min(1).max(80),subjectId:z.string().min(1).max(160),actionType:z.string().min(1).max(120),targetReference:z.string().max(1000).nullable().optional(),enforcementPoint:z.string().min(1).max(200),decision:z.enum(['ALLOW','BLOCK']),outcome:z.enum(['ALLOWED','BLOCKED','FAILED','UNAVAILABLE','UNKNOWN']),attemptedAt:z.iso.datetime(),completedAt:z.iso.datetime().nullable().optional(),providerReceipt:z.unknown()}).strict().parse(req.body);if(!config.ENFORCEMENT_WEBHOOK_SECRET||!config.ENFORCEMENT_SOURCE)return reply.code(503).send({error:'ENFORCEMENT_NOT_CONFIGURED'});if(b.enforcementPoint!==config.ENFORCEMENT_SOURCE)return reply.code(403).send({error:'UNTRUSTED_ENFORCEMENT_SOURCE'});const sig=req.headers['x-enforcement-signature'];if(typeof sig!=='string')return reply.code(401).send({error:'ENFORCEMENT_SIGNATURE_REQUIRED'});const payload=JSON.stringify(b);const expected=createHmac('sha256',config.ENFORCEMENT_WEBHOOK_SECRET).update(payload).digest('hex');const got=Buffer.from(sig,'hex'),want=Buffer.from(expected,'hex');if(got.length!==want.length||!timingSafeEqual(got,want))return reply.code(401).send({error:'INVALID_ENFORCEMENT_SIGNATURE'});const enforcementInput={organizationId:org,policyEvaluationId:b.policyEvaluationId,subjectType:b.subjectType,subjectId:b.subjectId,actionType:b.actionType,enforcementPoint:b.enforcementPoint,decision:b.decision,outcome:b.outcome,attemptedAt:b.attemptedAt,providerReceipt:b.providerReceipt,...(b.targetReference===undefined?{}:{targetReference:b.targetReference}),...(b.completedAt===undefined?{}:{completedAt:b.completedAt})};const a=await verifiedEnforcement(enforcementInput,kernelStore);await persistEnforcementAttempt(config.DATABASE_URL,a);return reply.code(201).send(a)});
app.post('/v1/governance/policies/:id/evaluate',async(req,reply)=>{if(!requireRole(req,reply,aiWriterRoles))return;const org=tenant(req,reply);if(!org)return;const q=z.object({version:z.coerce.number().int().positive()}).parse(req.query);const b=z.object({subjectType:z.string().min(1).max(80),subjectId:z.string().min(1).max(160),inputs:z.record(z.string(),z.unknown()),evidenceHashes:z.array(hash).max(100),evidenceIds:z.array(z.uuid()).max(100),evidenceState:z.enum(['SUPPORTED','PARTIAL','UNKNOWN','CONFLICTING','UNSUPPORTED']),enforcementMode:z.enum(['OBSERVE','ENFORCE']).default('OBSERVE')}).parse(req.body);const v=await governanceStore.evaluate(org,(req.params as{id:string}).id,q.version,b.subjectType,b.subjectId,b.inputs,b.evidenceHashes,b.evidenceState,b.enforcementMode);if(!v)return reply.code(404).send({error:'POLICY_NOT_FOUND'});await integrateEvidence(kernelStore,org,{domain:'GOVERNANCE',recordId:v.id,subjectType:b.subjectType,subjectId:b.subjectId,claimType:'POLICY_EVALUATION',claimText:v.explanation,findingType:'GOVERNANCE_EVALUATION',state:b.evidenceState,summary:v.explanation,evidenceIds:b.evidenceIds});return reply.code(201).send(v)});
app.post('/v1/ai', async (req, reply) => {
 if (!requireRole(req, reply, aiWriterRoles)) return;
 const organizationId = tenant(req, reply); if (!organizationId) return;
 const body = z.object({ name: z.string().trim().min(1).max(120), purpose: z.string().trim().min(1).max(500), owner: z.string().max(120).nullable().default(null), provider: z.string().max(120).nullable().default(null), model: z.string().max(120).nullable().default(null) }).parse(req.body);
 const created=await aiStore.register(organizationId, body); await inventoryStore.register(organizationId,created.id); return reply.code(201).send(created);
});
app.get('/v1/ai/:id', async (req, reply) => {
 if(!requireTenantRead(req,reply,true))return;
 const organizationId = tenant(req, reply); if (!organizationId) return;
 const system = await aiStore.get(organizationId, (req.params as { id: string }).id);
 if (!system) return reply.code(404).send({ error: 'NOT_FOUND' });
 const events = await aiStore.timeline(organizationId, system.id);
 return { ...system, observedEvents: events.length, monitoringStatus: 'NOT_CONNECTED', compliance: { state: 'HOLD', reason: 'No reviewed, applicable regulatory rule set or control evidence is configured.' }, evidenceCoverage: 'REPORTED_EVENTS_ONLY' };
});
app.post('/v1/ai/:id/events', async (req, reply) => {
 if (!requireRole(req, reply, aiWriterRoles)) return;
 const organizationId = tenant(req, reply); if (!organizationId) return;
 const body = z.object({ eventType: z.enum(['OUTPUT','TOOL_REQUEST','TOOL_RESULT','ACTION_REQUESTED','ACTION_CONFIRMED','ACTION_FAILED','ACTION_UNAVAILABLE','APPROVAL_REQUESTED','APPROVAL_GRANTED','APPROVAL_DENIED','CONFIG_CHANGED']), sourceType: z.enum(['DECLARATION','DIRECT_OBSERVATION','AUTHORITATIVE_SYSTEM','SIGNED_ATTESTATION']), source: z.string().min(1).max(200), summary: z.string().min(1).max(1000), occurredAt: z.iso.datetime({ offset: true }), evidenceHash: z.string().regex(/^[a-f0-9]{64}$/), evidenceIds:z.array(z.uuid()).max(100) }).parse(req.body);
 if (body.sourceType !== 'DECLARATION') return reply.code(400).send({ error: 'SOURCE_NOT_VERIFIED', message: 'External API submissions are declarations until a trusted connector verifies the source.' });
 if (Date.parse(body.occurredAt)>Date.now()+300000) return reply.code(400).send({error:'FUTURE_EVENT_NOT_ALLOWED'});
 if (['ACTION_CONFIRMED','ACTION_FAILED','ACTION_UNAVAILABLE','APPROVAL_GRANTED','APPROVAL_DENIED'].includes(body.eventType)) return reply.code(400).send({ error: 'TRUSTED_RESULT_REQUIRED' });
 if(!body.evidenceIds.length)return reply.code(400).send({error:'FLIGHT_EVENT_REQUIRES_CANONICAL_EVIDENCE'});const lineage=await Promise.all(body.evidenceIds.map(id=>kernelStore.bind(organizationId,id,'AI_FLIGHT',(req.params as {id:string}).id,'SUPPORTS')));if(lineage.some(ok=>!ok))return reply.code(400).send({error:'CANONICAL_EVIDENCE_REQUIRED'});const canonicalHash=createHash('sha256').update([...body.evidenceIds].sort().join(':')).digest('hex');if(body.evidenceHash!==canonicalHash)return reply.code(400).send({error:'EVIDENCE_HASH_DOES_NOT_MATCH_CANONICAL_IDS'});
 const event = await aiStore.append(organizationId, (req.params as { id: string }).id, body);
 return event ? reply.code(201).send(event) : reply.code(404).send({ error: 'NOT_FOUND' });
});
app.get('/v1/ai/:id/timeline', async (req, reply) => {
 if(!requireTenantRead(req,reply,true))return;
 const organizationId = tenant(req, reply); if (!organizationId) return;
 const id = (req.params as { id: string }).id;
 if (!await aiStore.get(organizationId, id)) return reply.code(404).send({ error: 'NOT_FOUND' });
 const query = z.object({ afterSequence: z.coerce.number().int().nonnegative().default(0), limit: z.coerce.number().int().min(1).max(500).default(100) }).parse(req.query);
 const page = await aiStore.timeline(organizationId, id, query.afterSequence, query.limit + 1);
 const hasMore = page.length > query.limit; const events = page.slice(0, query.limit);
 return { aiId: id, coverage: 'REPORTED_EVENTS_ONLY', order: 'INGESTION_SEQUENCE', hasMore, nextCursor: hasMore ? events.at(-1)?.sequence : null, events: events.map(e => ({ ...e, statement: `${e.occurredAt}: ${e.summary} (${e.eventType}; ${e.sourceType} from ${e.source}). Evidence SHA-256: ${e.evidenceHash}.` })) };
});
app.get('/v1/ai/:id/alerts', async (req, reply) => {
 if(!requireTenantRead(req,reply,true))return;
 const organizationId = tenant(req, reply); if (!organizationId) return;
 const id = (req.params as { id: string }).id;
 if (!await aiStore.get(organizationId, id)) return reply.code(404).send({ error: 'NOT_FOUND' });
 return { aiId: id, alerts: await aiStore.alerts(organizationId, id) };
});
app.get('/v1/ai/:id/integrity', async (req, reply) => {
 if(!requireTenantRead(req,reply,true))return;
 const organizationId = tenant(req, reply); if (!organizationId) return;
 const id = (req.params as { id: string }).id;
 if (!await aiStore.get(organizationId, id)) return reply.code(404).send({ error: 'NOT_FOUND' });
 return aiStore.integrity(organizationId, id);
});
app.get('/v1/ai/:id/coverage', async (req, reply) => {
 if(!requireTenantRead(req,reply,true))return;
 const organizationId = tenant(req, reply); if (!organizationId) return;
 const id = (req.params as { id: string }).id;
 if (!await aiStore.get(organizationId, id)) return reply.code(404).send({ error: 'NOT_FOUND' });
 const events = await aiStore.timeline(organizationId, id);
 return { aiId: id, state: 'UNKNOWN', scope: 'REGISTERED_AI_ONLY', sources: [
  { name: 'Submitted events', state: events.length ? 'DECLARED' : 'UNKNOWN', observedCount: events.filter(e => e.sourceType === 'DECLARATION').length },
  { name: 'Provider activity', state: 'UNAVAILABLE', reason: 'No provider activity connector is installed.' },
  { name: 'Tool execution', state: 'UNAVAILABLE', reason: 'No independent tool execution collector is installed.' },
  { name: 'Organization-wide AI discovery', state: 'UNAVAILABLE', reason: 'No organization discovery connector is installed.' }
 ] };
});
const confirmationSchema = z.object({ organizationId: z.string().min(1).max(100), aiId: z.uuid(), claimEventId: z.uuid(), outcome: z.enum(['CONFIRMED','FAILED','ABSENT','UNREACHABLE']), source: z.string().regex(/^[A-Za-z0-9_.:-]{1,100}$/), occurredAt: z.iso.datetime({ offset: true }), evidenceHash: z.string().regex(/^[a-f0-9]{64}$/), externalEventId: z.string().regex(/^[A-Za-z0-9_.:-]{1,150}$/) });
app.post('/v1/integrations/action-confirmations', async (req, reply) => {
 if (!config.TRUSTED_ACTION_WEBHOOK_SECRET || !config.TRUSTED_ACTION_SOURCE) return reply.code(503).send({ error: 'CONNECTOR_NOT_CONFIGURED' });
 const body = confirmationSchema.parse(req.body);
 if (body.source !== config.TRUSTED_ACTION_SOURCE) return reply.code(403).send({ error: 'UNTRUSTED_SOURCE' });
 const canonical = [body.organizationId, body.aiId, body.claimEventId, body.outcome, body.source, body.occurredAt, body.evidenceHash, body.externalEventId].join('\n');
 const expected = createHmac('sha256', config.TRUSTED_ACTION_WEBHOOK_SECRET).update(canonical).digest();
 const supplied = req.headers['x-media-signature'];
 if (typeof supplied !== 'string' || !/^[a-f0-9]{64}$/.test(supplied) || !timingSafeEqual(expected, Buffer.from(supplied, 'hex'))) return reply.code(401).send({ error: 'INVALID_CONNECTOR_SIGNATURE' });
 try {
  const result = await aiStore.confirm(body.organizationId, body.aiId, body); if(!result)return reply.code(404).send({ error: 'CLAIM_NOT_FOUND' });
  const canonicalEvidence=await kernelStore.record(body.organizationId,{sourceType:'AUTHORITATIVE_SYSTEM',sourceName:body.source,collector:'trusted-action-connector',subjectType:'AI',subjectId:body.aiId,observationType:'ACTION_CONFIRMATION',content:{claimEventId:body.claimEventId,outcome:body.outcome,externalEventId:body.externalEventId,evidenceHash:body.evidenceHash},observedAt:body.occurredAt,collectedAt:new Date().toISOString(),validationState:body.outcome==='UNREACHABLE'?'UNAVAILABLE':'VERIFIED',evidenceType:'ACTION_CONFIRMATION',provenance:{externalEventId:body.externalEventId}}); await integrateEvidence(kernelStore,body.organizationId,{domain:'AI_FLIGHT',recordId:result.event.id,subjectType:'AI',subjectId:body.aiId,claimType:result.event.eventType,claimText:result.event.summary,findingType:'AUTHORITATIVE_ACTION_RESULT',state:result.event.state==='CONFLICTING'?'CONFLICTING':result.event.state==='UNAVAILABLE'?'UNKNOWN':'SUPPORTED',summary:result.event.summary,evidenceIds:[canonicalEvidence.evidenceId]}); if(result.alert)await integrateEvidence(kernelStore,body.organizationId,{domain:'INCIDENT',recordId:result.alert.id,subjectType:'AI',subjectId:body.aiId,claimType:'AI_CONTRADICTION_INCIDENT',claimText:result.alert.summary,findingType:'AI_CONTRADICTION',state:'CONFLICTING',summary:result.alert.summary,evidenceIds:[canonicalEvidence.evidenceId]}); return reply.code(201).send(result);
 } catch (error) {
  if (error instanceof Error && error.message === 'DUPLICATE_CONFIRMATION' || typeof error === 'object' && error !== null && 'code' in error && error.code === '23505') return reply.code(409).send({ error: 'DUPLICATE_CONFIRMATION' });
  throw error;
 }
});
const verifyUpload = async (req: FastifyRequest, reply: FastifyReply) => {
  if (!requireRole(req, reply, ['creator','analyst','organization_admin','platform_admin','super_admin'])) return;
  const identity = auth(req); if (req.url === '/v1/publisher/verify' && !identity.organizationId) return reply.code(403).send({ error: 'PUBLISHER_KEY_REQUIRED' }); const declaredHeader = String(req.headers['x-declared-ai-use'] ?? 'UNKNOWN').toUpperCase(); const declaredAiUse = (aiStatuses as readonly string[]).includes(declaredHeader) ? declaredHeader as typeof aiStatuses[number] : 'UNKNOWN';
  const creatorHeader = req.headers['x-creator-id']; const creatorId = typeof creatorHeader === 'string' && idPattern.test(creatorHeader) ? creatorHeader : undefined;
  const scannerOk=await scannerReady(config.MALWARE_SCAN_URL,config.MALWARE_SCAN_TOKEN,config.MALWARE_SCAN_TIMEOUT_MS); if(!scannerOk){req.log.warn({state:'BLOCKED_UNVERIFIED'},'upload rejected because malware scanner is unavailable');return reply.code(503).send({error:'BLOCKED_UNVERIFIED',state:'BLOCKED_UNVERIFIED',reason:'MALWARE_SCANNER_UNAVAILABLE'});}
  const part = await req.file({ limits: { fileSize: config.MAX_UPLOAD_BYTES } }); if (!part) return reply.code(400).send({ error: 'FILE_REQUIRED' });
  const declared = (part.mimetype || 'application/octet-stream').split(';')[0]?.toLowerCase() || 'application/octet-stream';
  const upload = await storeUpload(part.file, part.filename, declared, config.UPLOAD_DIR, config.MAX_UPLOAD_BYTES);
  const processingOrg=identity.organizationId; const idempotencyHeader=req.headers['idempotency-key']; const idempotencyKey=typeof idempotencyHeader==='string'&&idempotencyHeader.trim()?idempotencyHeader.trim().slice(0,200):upload.id; let processingRun:{id:string;stage:string;assetId:string|null;attemptCount:number}|null=null;
  try {
    if(processingOrg){processingRun=await store.beginProcessing(processingOrg,idempotencyKey,upload.sha256);if(processingRun.attemptCount>1){if(processingRun.stage==='COMPLETED'&&processingRun.assetId){const prior=await store.get(processingRun.assetId,processingOrg);if(prior)return reply.code(200).send(req.url==='/v1/publisher/verify'?{passportId:prior.asset.id,assetSha256:prior.asset.sha256,decision:prior.decision,confidence:prior.confidence,aiStatus:prior.aiStatus,provenance:prior.provenance,evidence:prior.observations,limitations:prior.limitations,resultUrl:`/v1/media/${prior.asset.id}`,idempotentReplay:true}:{passportId:prior.asset.id,...prior,resultUrl:`/v1/media/${prior.asset.id}`,idempotentReplay:true});throw Error('IDEMPOTENT_REQUEST_IN_PROGRESS_OR_FAILED')}}}
    if (!config.MALWARE_SCAN_URL || !config.MALWARE_SCAN_TOKEN) throw new Error('MALWARE_SCANNER_NOT_CONFIGURED');
    await scanForMalware(upload.path, upload.sizeBytes, upload.mime, config.MALWARE_SCAN_URL, config.MALWARE_SCAN_TOKEN, config.MALWARE_SCAN_TIMEOUT_MS); if(processingOrg&&processingRun)await store.markProcessing(processingRun.id,processingOrg,'SCANNED_CLEAN',upload.id);
    const cleanUpload=await promoteStoredMedia(upload,config.UPLOAD_DIR);
    const asset = { id: upload.id, sha256: upload.sha256, mime: upload.mime, kind: upload.kind, sizeBytes: upload.sizeBytes, originalFilename: upload.originalFilename, createdAt: new Date().toISOString(), ...(identity.organizationId ? { organizationId: identity.organizationId } : {}), ...(creatorId ? { creatorId } : {}), declaredAiUse };
    const record = await verifyMedia(asset, cleanUpload.path, { verifyTrust: config.C2PA_VERIFY_TRUST, requireVerification: true }); if(processingOrg&&processingRun)await store.markProcessing(processingRun.id,processingOrg,'VERIFIED',asset.id); if(processingOrg){for(const observation of record.observations){const observedAt=observation.createdAt??record.createdAt??new Date().toISOString();const canonical=await kernelStore.record(processingOrg,{sourceType:'MEDIA_VERIFICATION',sourceName:observation.source,collector:observation.model?.name??'media-passport-engine',subjectType:'MEDIA_ASSET',subjectId:asset.id,observationType:observation.signal,content:{result:observation.result,confidence:observation.confidence??null,details:observation.details??null,contentHash:observation.contentHash??asset.sha256},observedAt,collectedAt:new Date().toISOString(),validationState:observation.result==='unavailable'?'UNAVAILABLE':'OBSERVED',evidenceType:'MEDIA_SIGNAL',provenance:{assetSha256:asset.sha256,model:observation.model??null}});const bound=await kernelStore.bind(processingOrg,canonical.evidenceId,'MEDIA',asset.id,'OBSERVES');if(!bound)throw Error('CANONICAL_EVIDENCE_BINDING_FAILED')}} await store.save(record); if(processingOrg&&processingRun)await store.markProcessing(processingRun.id,processingOrg,'PERSISTED',asset.id); if (config.DELETE_SOURCE_AFTER_VERIFICATION) await deleteStoredMedia(cleanUpload.path, config.UPLOAD_DIR);
    if(processingOrg&&processingRun)await store.markProcessing(processingRun.id,processingOrg,'COMPLETED',asset.id); return reply.code(201).send(req.url === '/v1/publisher/verify' ? { passportId: asset.id, assetSha256: asset.sha256, decision: record.decision, confidence: record.confidence, aiStatus: record.aiStatus, provenance: record.provenance, evidence: record.observations, limitations: record.limitations, resultUrl: `/v1/media/${asset.id}` } : { passportId: asset.id, ...record, resultUrl: `/v1/media/${asset.id}` });
  } catch (error) {
    await deleteStoredMedia(upload.path, config.UPLOAD_DIR).catch(()=>undefined); const cleanPath=resolve(config.UPLOAD_DIR,'clean',basename(upload.path)); await deleteStoredMedia(cleanPath, config.UPLOAD_DIR).catch((cleanupError) => req.log.error({ err: cleanupError, assetId: upload.id }, 'failed to remove media after verification failure'));
    const message = error instanceof Error ? error.message : String(error); if(processingOrg&&processingRun)await store.markProcessing(processingRun.id,processingOrg,'FAILED',upload.id,message.slice(0,120)).catch(()=>undefined); req.log.error({ err: error, assetId: upload.id }, 'verification failed'); const malware = message === 'MALWARE_DETECTED';
    return reply.code(malware ? 422 : 503).send({ error: malware ? 'MALWARE_DETECTED' : 'VERIFICATION_UNAVAILABLE' });
  }
};
app.post('/v1/media/verify', verifyUpload);
app.post('/v1/publisher/verify', verifyUpload);
async function getRecord(id: string, reply: any, identity?: ApiIdentity | null) { if (!idPattern.test(id)) { void reply.code(400).send({ error: 'INVALID_ID' }); return null; } const record = await store.get(id, identity?.organizationId ?? undefined); if (!record || (identity && !canReadTenantRecord(identity, record))) { void reply.code(404).send({ error: 'NOT_FOUND' }); return null; } return record; }
app.get('/v1/media/:id', async (req, reply) => { const record = await getRecord((req.params as { id: string }).id, reply, req.mediaAuth); if (!record) return; return record; });
app.get('/v1/media/:id/evidence', async (req, reply) => { const record = await getRecord((req.params as { id: string }).id, reply, req.mediaAuth); if (!record) return; return { passportId: record.asset.id, evidence: record.observations, evidenceQuality: record.trustVector.evidenceQuality }; });
app.get('/v1/media/:id/provenance', async (req, reply) => { const record = await getRecord((req.params as { id: string }).id, reply, req.mediaAuth); if (!record) return; return { passportId: record.asset.id, provenance: record.provenance }; });
app.get('/v1/media/:id/trust', async (req, reply) => { const record = await getRecord((req.params as { id: string }).id, reply, req.mediaAuth); if (!record) return; return { passportId: record.asset.id, trustScore: record.trustScore, confidence: record.confidence, vector: record.trustVector, decision: record.decision, limitations: record.limitations }; });
app.get('/v1/media/:id/claims', async (req, reply) => { const record = await getRecord((req.params as { id: string }).id, reply, req.mediaAuth); if (!record) return; return { passportId: record.asset.id, claims: [], status: 'NOT_ANALYZED', note: 'Claim extraction requires a configured source-analysis provider; no claims are fabricated.' }; });
app.post('/v1/media/:id/appeal', async (req, reply) => { if (!requireRole(req, reply, ['creator','organization_admin','platform_admin','super_admin'])) return; const record = await getRecord((req.params as { id: string }).id, reply, req.mediaAuth); if (!record) return; const body = z.object({ reason: z.string().min(10).max(5000), evidence: z.array(z.string().max(2000)).max(20).default([]) }).parse(req.body); const organizationId=tenant(req,reply);if(!organizationId)return;const created=await store.createAppeal(organizationId,record.asset.id,body.reason,body.evidence);return reply.code(202).send({ status: 'accepted', passportId: record.asset.id, caseId: created.id, nextStep: 'human_review' }); });
app.post('/v1/media/:id/report', async (req, reply) => { const record = await getRecord((req.params as { id: string }).id, reply, req.mediaAuth); if (!record) return; const body = z.object({ category: z.enum(['impersonation','copyright','privacy','deception','spam','other']), description: z.string().min(10).max(5000) }).parse(req.body); const organizationId=tenant(req,reply);if(!organizationId)return;const created=await store.createReport(organizationId,record.asset.id,body.category,body.description);return reply.code(202).send({ status: 'accepted', passportId: record.asset.id, caseId: created.id }); });
app.post('/v1/recommendation/evaluate', async (req, reply) => { if (!requireRole(req, reply, ['analyst','moderator','organization_admin','platform_admin','super_admin'])) return; const body = z.object({ passportId: z.string().min(10).max(40), minTrust: z.number().min(0).max(100).default(70), requireProvenance: z.boolean().default(false), requireDisclosure: z.boolean().default(true) }).parse(req.body); const record = await getRecord(body.passportId, reply, req.mediaAuth); if (!record) return; const eligible = (record.trustScore ?? 0) >= body.minTrust && (!body.requireProvenance || record.provenance.status === 'verified') && (!body.requireDisclosure || !record.limitations.some(x => /disclosure/i.test(x))); return { passportId: record.asset.id, eligible, decision: record.decision, trustScore: record.trustScore, confidence: record.confidence, reasons: eligible ? ['Trust threshold met', 'No blocking decision'] : ['Recommendation criteria not satisfied'], explainability: { trust: record.trustVector, provenance: record.provenance.status, aiStatus: record.aiStatus } }; });
app.get('/public/:id', async (_req, reply) => reply.code(404).send({ error: 'NOT_FOUND' }));
app.get('/passport/:id', async (_req, reply) => reply.code(404).send({ error: 'NOT_FOUND' }));
app.setErrorHandler((error, req, reply) => { if (error instanceof z.ZodError) return reply.code(400).send({ error: 'INVALID_REQUEST', issues: error.issues }); const message = error instanceof Error ? error.message : String(error); if ((error as { code?: string }).code === 'FST_REQ_FILE_TOO_LARGE' || message === 'UPLOAD_TOO_LARGE') return reply.code(413).send({ error: 'UPLOAD_TOO_LARGE' }); if (message === 'UNSUPPORTED_MEDIA_TYPE') return reply.code(415).send({ error: message }); if (message === 'MIME_MISMATCH') return reply.code(400).send({ error: message }); req.log.error({ err: error }, 'request failed'); return reply.code(500).send({ error: 'INTERNAL_ERROR' }); });
const shutdown = async (signal: string) => { app.log.info({ signal }, 'shutting down'); await app.close(); await store.close(); await aiStore.close(); await constellationStore.close(); await accountabilityStore.close(); await kernelStore.close(); process.exit(0); };
process.once('SIGTERM', () => void shutdown('SIGTERM')); process.once('SIGINT', () => void shutdown('SIGINT')); await app.listen({ host: config.HOST, port: config.PORT });
