import{evidenceDigest,type CollectorObservation}from'./collectors.js';
import{lookup}from'node:dns/promises';
import{request}from'node:https';
import{isIP}from'node:net';
export type DiscoveryProvider='OPENAI'|'ANTHROPIC'|'AI_GATEWAY'|'SAAS_INVENTORY';
export interface HttpDiscoveryConfig{provider:DiscoveryProvider;baseUrl:string;token:string;path:string;timeoutMs?:number;maxBytes?:number}
type Row={provider?:string;model?:string;application?:string;workflow?:string;environment?:string;externalId?:string;observedAt?:string};
const arr=(x:unknown):unknown[]=>Array.isArray(x)?x:x&&typeof x==='object'&&Array.isArray((x as any).data)?(x as any).data:x&&typeof x==='object'&&Array.isArray((x as any).items)?(x as any).items:[];
const clean=(v:unknown)=>{if(typeof v!=='string')return undefined;if(v.length>500||/[\u0000-\u001f\u007f]/.test(v))return undefined;return v.normalize('NFC')};
function row(x:unknown):Row|null{if(!x||typeof x!=='object')return null;const v=x as Record<string,unknown>;const pairs=[['provider',clean(v.provider)],['model',clean(v.model)??clean(v.model_name)],['application',clean(v.application)??clean(v.app)??clean(v.service)],['workflow',clean(v.workflow)],['environment',clean(v.environment)],['externalId',clean(v.id)??clean(v.external_id)],['observedAt',clean(v.observed_at)??clean(v.timestamp)]] as const;return Object.fromEntries(pairs.filter(([,v])=>v!==undefined)) as Row}
export function isPrivateAddress(address:string){if(isIP(address)===4){const p=address.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||p[0]===169&&p[1]===254||p[0]===192&&p[1]===168||p[0]===172&&p[1]>=16&&p[1]<=31||p[0]===100&&p[1]>=64&&p[1]<=127||p[0]>=224}const a=address.toLowerCase();return a==='::'||a==='::1'||a.startsWith('fc')||a.startsWith('fd')||a.startsWith('fe8')||a.startsWith('fe9')||a.startsWith('fea')||a.startsWith('feb')||a.startsWith('ff')||a.startsWith('::ffff:127.')||a.startsWith('::ffff:10.')||a.startsWith('::ffff:192.168.')||/^::ffff:172\.(1[6-9]|2\d|3[01])\./.test(a)}
export function safeBase(raw:string){const u=new URL(raw);if(u.protocol!=='https:')throw Error('COLLECTOR_HTTPS_REQUIRED');if(u.username||u.password)throw Error('COLLECTOR_URL_CREDENTIALS_FORBIDDEN');const h=u.hostname.toLowerCase();if(h==='localhost'||h.endsWith('.local')||isIP(h)&&isPrivateAddress(h))throw Error('COLLECTOR_PRIVATE_NETWORK_FORBIDDEN');return u}
async function resolvePublic(hostname:string){const addresses=await lookup(hostname,{all:true,verbatim:true});if(!addresses.length)throw Error('COLLECTOR_DNS_EMPTY');if(addresses.some(x=>isPrivateAddress(x.address)))throw Error('COLLECTOR_PRIVATE_NETWORK_FORBIDDEN');return addresses[0]!}
async function pinnedHttpsGet(u:URL,token:string,timeoutMs:number,maxBytes:number){const pinned=await resolvePublic(u.hostname);return new Promise<{status:number;body:string}>((resolve,reject)=>{const req=request(u,{method:'GET',headers:{authorization:`Bearer ${token}`,accept:'application/json',host:u.host},servername:u.hostname,lookup:(_hostname,_options,cb)=>cb(null,pinned.address,pinned.family)},res=>{const status=res.statusCode??0;if(status>=300&&status<400){res.resume();reject(Error('COLLECTOR_REDIRECT_FORBIDDEN'));return}let n=0;const chunks:Buffer[]=[];res.on('data',(b:Buffer|string)=>{const chunk=Buffer.isBuffer(b)?b:Buffer.from(b);n+=chunk.length;if(n>maxBytes){req.destroy(Error('COLLECTOR_RESPONSE_TOO_LARGE'));return}chunks.push(chunk)});res.on('end',()=>resolve({status,body:Buffer.concat(chunks).toString('utf8')}))});req.setTimeout(timeoutMs,()=>req.destroy(Error('COLLECTOR_TIMEOUT')));req.on('error',reject);req.end()})}
export function httpDiscoveryCollector(c:HttpDiscoveryConfig){const version='1';return{key:`shadow-ai:${c.provider.toLowerCase()}`,version,async collect(subject:{type:string;id:string}):Promise<CollectorObservation<{rows:Row[]}>>{const at=new Date().toISOString();const base=safeBase(c.baseUrl);const u=new URL(c.path,base);if(u.origin!==base.origin)throw Error('COLLECTOR_CROSS_ORIGIN_PATH_FORBIDDEN');const r=await pinnedHttpsGet(u,c.token,c.timeoutMs??10000,c.maxBytes??2_000_000);if(r.status<200||r.status>=300)throw Error(`COLLECTOR_HTTP_${r.status}`);let parsed:unknown;try{parsed=JSON.parse(r.body)}catch{throw Error('COLLECTOR_INVALID_JSON')}const rows=arr(parsed).map(row).filter((x):x is Row=>!!x);if(!rows.length)return{collectorKey:`shadow-ai:${c.provider.toLowerCase()}`,collectorVersion:version,subjectType:subject.type,subjectId:subject.id,health:'HEALTHY',coverage:'PARTIAL',observedAt:at,collectedAt:new Date().toISOString(),payload:{rows:[]},evidenceHash:evidenceDigest({collectorKey:`shadow-ai:${c.provider.toLowerCase()}`,collectorVersion:version,subjectType:subject.type,subjectId:subject.id,health:'HEALTHY',coverage:'PARTIAL',observedAt:at,payload:{rows:[]},limitations:['Provider responded but no supported discovery records were observable; absence is not proof of no AI usage.']}),limitations:['Provider responded but no supported discovery records were observable; absence is not proof of no AI usage.']};const collectedAt=new Date().toISOString();for(const x of rows){if(x.observedAt){const ts=Date.parse(x.observedAt);if(!Number.isFinite(ts)||ts>Date.parse(collectedAt)+300000)throw Error('COLLECTOR_ROW_INVALID_CHRONOLOGY')}}const limitations=['Coverage is bounded to this configured provider surface and returned records.'];return{collectorKey:`shadow-ai:${c.provider.toLowerCase()}`,collectorVersion:version,subjectType:subject.type,subjectId:subject.id,health:'HEALTHY',coverage:'OBSERVED',observedAt:at,collectedAt,payload:{rows},evidenceHash:evidenceDigest({collectorKey:`shadow-ai:${c.provider.toLowerCase()}`,collectorVersion:version,subjectType:subject.type,subjectId:subject.id,health:'HEALTHY',coverage:'OBSERVED',observedAt:at,payload:{rows},limitations}),limitations}}}}
