import{createHash,createHmac,randomUUID}from'node:crypto';import postgres from'postgres';import{assertPublicHttps}from'./security-gate.js';
export type DeliveryStatus='DELIVERED'|'RETRY'|'DEAD';
export interface DeliveryPolicy{maxAttempts:number;baseDelayMs:number;maxDelayMs:number;timeoutMs:number;maxRequestBytes:number;maxResponseBytes:number;leaseMs:number}
export const defaultDeliveryPolicy:DeliveryPolicy={maxAttempts:8,baseDelayMs:1000,maxDelayMs:3600000,timeoutMs:10000,maxRequestBytes:1000000,maxResponseBytes:65536,leaseMs:30000};
export const retryDelay=(attempt:number,p:DeliveryPolicy=defaultDeliveryPolicy)=>Math.min(p.maxDelayMs,p.baseDelayMs*2**Math.max(0,attempt-1));
export const classify=(attempt:number,status:number|null,p:DeliveryPolicy=defaultDeliveryPolicy):DeliveryStatus=>{
 if(status!==null&&status>=200&&status<300)return'DELIVERED';
 if(attempt>=p.maxAttempts)return'DEAD';
 if(status!==null&&status>=400&&status<500&&status!==408&&status!==409&&status!==425&&status!==429)return'DEAD';
 return'RETRY';
};
export function signature(secret:string,keyId:string,deliveryId:string,timestamp:string,body:string){const canonical=[deliveryId,timestamp,body].join('.');return{keyId,deliveryId,timestamp,value:createHmac('sha256',secret).update(canonical).digest('hex')}}
const sha=(x:string)=>createHash('sha256').update(x).digest('hex');
export class WebhookDeliveryStore{
 private sql;constructor(url:string){this.sql=postgres(url,{prepare:false})}
 async close(){await this.sql.end({timeout:5})}
 private async tenant<T>(org:string,fn:(tx:postgres.TransactionSql)=>Promise<T>):Promise<T>{if(!org)throw Error('TENANT_REQUIRED');return await this.sql.begin(async tx=>{await tx`SELECT set_config('app.organization_id',${org},true)`;return fn(tx)}) as T}
 async tenantIds(){const r=await this.sql`SELECT id FROM organizations ORDER BY id`;return r.map((x:any)=>String(x.id))}
 async claim(org:string,limit:number,leaseMs:number){const token=randomUUID();const rows=await this.tenant(org,tx=>tx`WITH due AS (SELECT id FROM webhook_outbox WHERE organization_id=${org} AND status IN('PENDING','FAILED') AND next_attempt_at<=now() AND (lease_expires_at IS NULL OR lease_expires_at<now()) ORDER BY next_attempt_at,id FOR UPDATE SKIP LOCKED LIMIT ${limit}) UPDATE webhook_outbox o SET lease_token=${token},lease_expires_at=now()+${leaseMs}*interval '1 millisecond' FROM due WHERE o.id=due.id AND o.organization_id=${org} RETURNING o.*`);return{token,rows}}
 async signingKey(org:string){const r=await this.tenant(org,tx=>tx`SELECT id,secret FROM webhook_signing_keys WHERE organization_id=${org} AND status='ACTIVE' AND not_before<=now() AND (not_after IS NULL OR not_after>now()) LIMIT 1`);return r[0] as {id:string;secret:string}|undefined}
 async subscription(id:string,org:string){const r=await this.tenant(org,tx=>tx`SELECT id,url FROM webhook_subscriptions WHERE id=${id} AND organization_id=${org} AND active=true LIMIT 1`);return r[0] as {id:string;url:string}|undefined}
 async finish(input:{row:any;token:string;deliveryId:string;keyId:string;requestHash:string;status:number|null;error:string|null;startedAt:string;completedAt:string;policy:DeliveryPolicy}){
  const attempt=Number(input.row.attempt_count)+1,decision=classify(attempt,input.status,input.policy),next=new Date(Date.parse(input.completedAt)+retryDelay(attempt,input.policy)).toISOString();
  await this.sql.begin(async tx=>{const locked=await tx`SELECT id FROM webhook_outbox WHERE id=${input.row.id} AND lease_token=${input.token} FOR UPDATE`;if(!locked.length)throw Error('WEBHOOK_LEASE_LOST');
   await tx`INSERT INTO webhook_delivery_attempts(id,organization_id,outbox_id,attempt_number,request_hash,response_status,error_class,started_at,completed_at,delivery_id,signature_key_id,next_attempt_at) VALUES(${randomUUID()},${input.row.organization_id},${input.row.id},${attempt},${input.requestHash},${input.status},${input.error},${input.startedAt},${input.completedAt},${input.deliveryId},${input.keyId},${decision==='RETRY'?next:null})`;
   if(decision==='DELIVERED')await tx`UPDATE webhook_outbox SET status='DELIVERED',attempt_count=${attempt},last_attempt_at=${input.completedAt},last_status_code=${input.status},last_error=NULL,delivered_at=${input.completedAt},lease_token=NULL,lease_expires_at=NULL WHERE id=${input.row.id}`;
   else if(decision==='DEAD'){await tx`UPDATE webhook_outbox SET status='DEAD',attempt_count=${attempt},last_attempt_at=${input.completedAt},last_status_code=${input.status},last_error=${input.error},dead_at=${input.completedAt},lease_token=NULL,lease_expires_at=NULL WHERE id=${input.row.id}`;await tx`INSERT INTO webhook_dead_letter_events(id,organization_id,outbox_id,action,reason,actor) VALUES(${randomUUID()},${input.row.organization_id},${input.row.id},'DEAD',${input.error??('HTTP_'+input.status)},'delivery-worker')`;}
   else await tx`UPDATE webhook_outbox SET status='FAILED',attempt_count=${attempt},next_attempt_at=${next},last_attempt_at=${input.completedAt},last_status_code=${input.status},last_error=${input.error},lease_token=NULL,lease_expires_at=NULL WHERE id=${input.row.id}`;
  });return{decision,attempt,nextAttemptAt:decision==='RETRY'?next:null}
 }
 async requeue(org:string,id:string,actor:string){return this.sql.begin(async tx=>{const r=await tx`UPDATE webhook_outbox SET status='PENDING',attempt_count=0,next_attempt_at=now(),last_error=NULL,dead_at=NULL,requeue_count=requeue_count+1,lease_token=NULL,lease_expires_at=NULL WHERE id=${id} AND organization_id=${org} AND status='DEAD' RETURNING id`;if(!r.length)return false;await tx`INSERT INTO webhook_dead_letter_events(id,organization_id,outbox_id,action,reason,actor) VALUES(${randomUUID()},${org},${id},'REQUEUED','operator requeue',${actor})`;return true})}
 async history(org:string,id:string){return this.sql`SELECT attempt_number,response_status,error_class,started_at,completed_at,delivery_id,signature_key_id,next_attempt_at FROM webhook_delivery_attempts WHERE organization_id=${org} AND outbox_id=${id} ORDER BY attempt_number`}
 async health(org:string){const r=await this.sql`SELECT status,count(*)::int count,min(created_at) oldest FROM webhook_outbox WHERE organization_id=${org} GROUP BY status`;return r}
}
export async function deliverClaimed(store:WebhookDeliveryStore,claim:{token:string;rows:any[]},policy:DeliveryPolicy=defaultDeliveryPolicy,fetcher:typeof fetch=fetch){
 const results=[];for(const row of claim.rows){const startedAt=new Date().toISOString(),deliveryId=String(row.id);let status:number|null=null,error:string|null=null,keyId='';let body='';try{const key=await store.signingKey(row.organization_id);if(!key)throw Error('SIGNING_KEY_UNAVAILABLE');keyId=key.id;const sub=await store.subscription(row.subscription_id,row.organization_id);if(!sub)throw Error('SUBSCRIPTION_UNAVAILABLE');assertPublicHttps(sub.url);body=JSON.stringify(row.payload);if(Buffer.byteLength(body)>policy.maxRequestBytes)throw Error('WEBHOOK_PAYLOAD_TOO_LARGE');const signed=signature(key.secret,key.id,deliveryId,startedAt,body);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),policy.timeoutMs);try{const res=await fetcher(sub.url,{method:'POST',headers:{'content-type':'application/json','user-agent':'MEDIA-Webhook/1.0','x-media-delivery-id':deliveryId,'x-media-timestamp':startedAt,'x-media-key-id':signed.keyId,'x-media-signature':'v1='+signed.value,'idempotency-key':deliveryId},body,signal:controller.signal,redirect:'error'});status=res.status;const reader=res.body?.getReader();let n=0;if(reader){for(;;){const x=await reader.read();if(x.done)break;n+=x.value.byteLength;if(n>policy.maxResponseBytes){error='RESPONSE_TOO_LARGE';status=null;await reader.cancel();break}}}}finally{clearTimeout(timer)}}catch(e){error=e instanceof Error?e.message.slice(0,200):'DELIVERY_ERROR'}const completedAt=new Date().toISOString();results.push(await store.finish({row,token:claim.token,deliveryId,keyId:keyId||'unavailable',requestHash:sha(body),status,error,startedAt,completedAt,policy}))}return results
}
